syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

package orbit.config;

message orbit_agent_cfg {
  string region = 1;
  string tag = 2;
  string configured_client_command_line = 3;
  double cpu_capacity = 4;
  double memory_capacity_mb = 5;
  uint32 server_identity_timeout_sec = 6;
  uint32 server_identity_check_interval_sec = 7;
  int32 max_batch_startup_count = 8;

  bool enable_seed_mode = 21;
  uint32 seed_startup_timeout_sec = 22;
  uint32 seed_heartbeat_timeout_sec = 23;
  string seed_client_command_line = 24;
}
