syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "protocol/extension/atframework.proto";

import "protocol/common/com.struct.team.common.proto";
import "protocol/pbdesc/com.struct.team.proto";

option go_package = "github.com/atframework/atsf4g-co/service-teamsvr/protocol/match/protocol/pbdesc";

package atframework.team;

message SSTeamMatchSearchReq {
  // team_matching_data matching_data = 1;
  // TODO(owent): implement me
}

message SSTeamMatchSearchRsp {
  int32 client_result = 1;
  // DTeamMatchData match_data = 2;
  DTeamKey team_key = 3;
  // TODO(owent): implement me
}

service TeamMatchService {
  option (atframework.service_options) = {
    module_name: "team"
  };

  rpc search(SSTeamMatchSearchReq) returns (SSTeamMatchSearchRsp) {
    option (atframework.rpc_options) = {
      api_name: "寻找队友"
      allow_no_wait: true
    };
  };
}
