# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: matchsvrd

type_id: 14
type_name: "matchsvr"

image:
  repository: harbor.m-oa.com:6023/project-x/matchsvr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/matchsvr/cfg
  logMountPath: /data/atframework/publish/matchsvr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/matchsvr/log

redis:
  enabled: true

cachesvr_shared:
  enabled: true

enable_excel_config: true
