# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: teamsvr-matchd

type_id: 19
type_name: "teamsvr-match"

image:
  repository: harbor.atframe.work/atsf4g-co/teamsvr-match
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/teamsvr-match/cfg
  logMountPath: /data/atframework/publish/teamsvr-match/log

vector:
  enabled: false
  log_path: /data/atframework/publish/teamsvr-match/log

redis:
  enable: true

enable_excel_config: true
