<#
.SYNOPSIS
    Forcefully kill all deployed service processes.
.DESCRIPTION
    Generated by `atdtool template --mode deploy_script`. Do not edit manually.
    Kills every running process whose executable is under a deployed service bin directory.
.PARAMETER Help
    Print help message and exit.
.PARAMETER DeployBaseDirectory
    Deploy base directory. Defaults to the directory containing this script.
.EXAMPLE
    .\kill_all.ps1
    pwsh -File .\kill_all.ps1 -d <deploy_base_dir>
    Get-Help .\kill_all.ps1 -detailed
    Get-Help .\kill_all.ps1 -full
#>

[CmdletBinding()]
param (
    [Parameter(ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [switch]$Help,

    [Parameter(ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [Alias('d')]
    [string]$DeployBaseDirectory = (Split-Path -Parent $PSCommandPath)
)

$ErrorActionPreference = 'Stop'
$PSDefaultParameterValues['*:Encoding'] = 'utf8'

function Show-Help {
    Write-Host ('usage: {0} [-d deploy_base_dir]' -f (Split-Path -Leaf $PSCommandPath))
    Write-Host 'Forcefully kills processes whose executable is under a deployed service bin directory.'
}

if ($Help) {
    Show-Help
    exit 0
}

if (-not (Test-Path -LiteralPath $DeployBaseDirectory -PathType Container)) {
    Write-Host ('[ERROR] Deploy base directory does not exist: "{0}"' -f $DeployBaseDirectory)
    exit 1
}
$DeployBaseDirectory = (Resolve-Path -LiteralPath $DeployBaseDirectory).ProviderPath

$TargetPaths = @(
{{ range $group := .Values.proc_groups }}{{ range $proc := $group.procs }}    $BinDir = Join-Path $DeployBaseDirectory '{{ $proc.name }}\bin'
    if (Test-Path -LiteralPath $BinDir -PathType Container) {
        Get-ChildItem -LiteralPath $BinDir -File -Filter '*.exe' |
            ForEach-Object { [System.IO.Path]::GetFullPath($_.FullName) }
    }
{{ end }}{{ end }})
if ($TargetPaths.Count -eq 0) {
    Write-Host ('[INFO] No executable files found under deployed service bin directories in {0}.' -f $DeployBaseDirectory)
    exit 0
}

$TargetSet = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
$TargetPaths | ForEach-Object { [void]$TargetSet.Add($_) }

$Processes = @(
    Get-CimInstance Win32_Process | Where-Object {
        $_.ExecutablePath -and $TargetSet.Contains([System.IO.Path]::GetFullPath($_.ExecutablePath))
    }
)
foreach ($Process in $Processes) {
    Write-Host ('[INFO] Killing {0} (pid {1})' -f $Process.ExecutablePath, $Process.ProcessId)
    taskkill.exe /F /T /PID $Process.ProcessId *> $null
}

Write-Host '[INFO] Kill all completed.'
exit 0