#!/bin/bash
#
# Generated by `atdtool template --mode deploy_script` from the tools chart.
# Do not edit manually. Edit the tools chart templates instead, then re-run
# install/tools/script/generate_config.sh.

DEPLOY_BASE_DIR="$(cd "$(dirname "$0")" && pwd -P)"

print_usage() {
  echo "usage: $0 [-d deploy_base_dir]"
  echo "Each batch is one group; entries in the same batch start in parallel."
}

start_otel_collector() {
  local otel_bin_dir="${DEPLOY_BASE_DIR}/otelcol/bin"
  local otel_exe="${otel_bin_dir}/otelcol-contrib"
  if [[ ! -e "$otel_exe" ]]; then
    echo "[INFO] Otel collector not found, skipped."
    return 0
  fi

  if pgrep -x otelcol-contrib >/dev/null 2>&1; then
    echo "[INFO] Otel collector already started, skipped."
    return 0
  fi

  if [[ ! -d "${DEPLOY_BASE_DIR}/otelcol/log" ]]; then
    mkdir -p "${DEPLOY_BASE_DIR}/otelcol/log"
  fi

  echo "[INFO] Starting otel collector: ${otel_exe}"
  (
    cd "$otel_bin_dir" || exit 1
    nohup ./otelcol-contrib --config=../cfg/config.yaml >> ../log/otelcol.log 2>&1 &
  )
  echo "[INFO] Otel collector started."
  return 0
}

run_batch() {
  local batch_index="$1"
  shift
  local entries=("$@")
  local scripts=()
  local labels=()
  local pids=()
  local entry=""
  local service_name=""
  local bus_addr=""
  local start_script=""
  local script_index=0
  local exit_code=0
  local failed=0

  if [[ ${#entries[@]} -eq 0 ]]; then
    echo "[INFO] Batch ${batch_index} does not contain any entry, skipped."
    return 0
  fi

  echo "[INFO] Batch ${batch_index}: ${entries[*]}"

  for entry in "${entries[@]}"; do
    service_name="${entry%% *}"
    bus_addr="${entry##* }"
    start_script="${DEPLOY_BASE_DIR}/${service_name}/bin/start_${bus_addr}.sh"
    if [[ ! -f "$start_script" ]]; then
      echo "[ERROR] Missing start script: ${start_script}" >&2
      return 1
    fi
    scripts+=("$start_script")
    labels+=("$start_script")
  done

  for start_script in "${scripts[@]}"; do
    echo "[INFO] Starting ${start_script}"
    bash "$start_script" &
    pids+=("$!")
  done

  for script_index in "${!pids[@]}"; do
    if wait "${pids[$script_index]}"; then
      echo "[INFO] Completed: ${labels[$script_index]}"
    else
      exit_code=$?
      echo "[ERROR] Failed: ${labels[$script_index]} (exit ${exit_code})" >&2
      failed=1
    fi
  done

  if [[ $failed -ne 0 ]]; then
    return 1
  fi

  return 0
}

while getopts "d:h" option; do
  case "$option" in
    d)
      if [[ ! -d "$OPTARG" ]]; then
        echo "[ERROR] Deploy base directory does not exist: $OPTARG" >&2
        exit 1
      fi
      DEPLOY_BASE_DIR="$(cd "$OPTARG" && pwd -P)"
      ;;
    h)
      print_usage
      exit 0
      ;;
    ?)
      print_usage >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

start_otel_collector

{{ range $group := .Values.proc_groups }}
if ! run_batch {{ $group.group }}{{ range $proc := $group.procs }}{{ range $instance := $proc.instances }} "{{ $proc.name }} {{ $instance.bus_addr }}"{{ end }}{{ end }}; then
  echo "[ERROR] Batch {{ $group.group }} failed." >&2
  exit 1
fi
{{ end }}

echo "[INFO] All batches completed successfully."
