#!/bin/bash
#
# Generated by `atdtool template --mode deploy_script` from the tools chart.
# Do not edit manually. Edit the tools chart templates instead, then re-run
# install/tools/script/generate_config.sh.

DEPLOY_BASE_DIR="$(cd "$(dirname "$0")" && pwd -P)"

print_usage() {
  echo "usage: $0 [-d deploy_base_dir]"
  echo "Batches stop in reverse group order; entries in the same batch stop in parallel."
}

stop_otel_collector() {
  local otel_bin_dir="${DEPLOY_BASE_DIR}/otelcol/bin"
  if [[ ! -d "$otel_bin_dir" ]]; then
    echo "[INFO] Otel collector not found, skipped."
    return 0
  fi

  if ! pgrep -x otelcol-contrib >/dev/null 2>&1; then
    echo "[INFO] Otel collector not running, skipped."
    return 0
  fi

  echo "[INFO] Stopping otel collector."
  pkill -x otelcol-contrib 2>/dev/null

  local wait_count=0
  while pgrep -x otelcol-contrib >/dev/null 2>&1; do
    if [[ $wait_count -ge 50 ]]; then
      echo "[WARNING] Otel collector still running after waiting." >&2
      return 1
    fi
    sleep 0.1
    wait_count=$((wait_count + 1))
  done

  echo "[INFO] Otel collector stopped."
  return 0
}

run_batch() {
  local batch_index="$1"
  shift
  local entries=("$@")
  local scripts=()
  local labels=()
  local pids=()
  local entry=""
  local service_name=""
  local bus_addr=""
  local stop_script=""
  local script_index=0
  local exit_code=0
  local failed=0

  if [[ ${#entries[@]} -eq 0 ]]; then
    echo "[INFO] Batch ${batch_index} does not contain any entry, skipped."
    return 0
  fi

  echo "[INFO] Batch ${batch_index}: ${entries[*]}"

  for entry in "${entries[@]}"; do
    service_name="${entry%% *}"
    bus_addr="${entry##* }"
    stop_script="${DEPLOY_BASE_DIR}/${service_name}/bin/stop_${bus_addr}.sh"
    if [[ ! -f "$stop_script" ]]; then
      echo "[ERROR] Missing stop script: ${stop_script}" >&2
      return 1
    fi
    scripts+=("$stop_script")
    labels+=("$stop_script")
  done

  for stop_script in "${scripts[@]}"; do
    echo "[INFO] Stopping ${stop_script}"
    bash "$stop_script" &
    pids+=("$!")
  done

  for script_index in "${!pids[@]}"; do
    if wait "${pids[$script_index]}"; then
      echo "[INFO] Completed: ${labels[$script_index]}"
    else
      exit_code=$?
      echo "[ERROR] Failed: ${labels[$script_index]} (exit ${exit_code})" >&2
      failed=1
    fi
  done

  if [[ $failed -ne 0 ]]; then
    return 1
  fi

  return 0
}

while getopts "d:h" option; do
  case "$option" in
    d)
      if [[ ! -d "$OPTARG" ]]; then
        echo "[ERROR] Deploy base directory does not exist: $OPTARG" >&2
        exit 1
      fi
      DEPLOY_BASE_DIR="$(cd "$OPTARG" && pwd -P)"
      ;;
    h)
      print_usage
      exit 0
      ;;
    ?)
      print_usage >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

{{ range $group := reverse .Values.proc_groups }}
if ! run_batch {{ $group.group }}{{ range $proc := $group.procs }}{{ range $instance := $proc.instances }} "{{ $proc.name }} {{ $instance.bus_addr }}"{{ end }}{{ end }}; then
  echo "[ERROR] Batch {{ $group.group }} failed." >&2
  exit 1
fi
{{ end }}

stop_otel_collector

echo "[INFO] All batches completed successfully."