<#
.SYNOPSIS
    Stop all service batches generated from the tools chart.
.DESCRIPTION
    Generated by `atdtool template --mode deploy_script`. Do not edit manually.
    Batches stop in reverse group order, entries in the same batch stop in
    parallel, and the script fails fast when any entry fails.
    The OpenTelemetry collector (otelcol/bin) is stopped last when running.
.PARAMETER Help
    Print help message and exit.
.PARAMETER DeployBaseDirectory
    Deploy base directory. Defaults to the directory containing this script.
.EXAMPLE
    .\stop_all.ps1
    pwsh -File .\stop_all.ps1 -d <deploy_base_dir>
    Get-Help .\stop_all.ps1 -detailed
    Get-Help .\stop_all.ps1 -full
#>

[CmdletBinding()]
param (
    [Parameter(ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [switch]$Help,

    [Parameter(ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [Alias('d')]
    [string]$DeployBaseDirectory = (Split-Path -Parent $PSCommandPath)
)

$ErrorActionPreference = 'Stop'
$PSDefaultParameterValues['*:Encoding'] = 'utf8'

function Show-Help {
    Write-Host ('usage: {0} [-d deploy_base_dir]' -f (Split-Path -Leaf $PSCommandPath))
    Write-Host 'Batches stop in reverse group order; entries in the same batch stop in parallel.'
}

function Get-ScriptHostExecutable {
    $PwshCommand = Get-Command 'pwsh' -ErrorAction SilentlyContinue
    if ($null -ne $PwshCommand) {
        return $PwshCommand.Source
    }
    return (Get-Command 'powershell' -ErrorAction Stop).Source
}

function Invoke-ScriptsInParallel {
    param (
        [string[]]$ScriptPaths,
        [string]$ActionLabel
    )

    if ($ScriptPaths.Count -eq 0) {
        Write-Host '[ERROR] Batch does not contain any script.'
        return $false
    }

    $ScriptHostExecutable = Get-ScriptHostExecutable
    $Jobs = @()
    foreach ($ScriptPath in $ScriptPaths) {
        Write-Host ('[INFO] {0} {1}' -f $ActionLabel, $ScriptPath)
        $Process = Start-Process -FilePath $ScriptHostExecutable `
            -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $ScriptPath) `
            -WorkingDirectory (Split-Path -Parent $ScriptPath) -PassThru -NoNewWindow
        if ($null -eq $Process) {
            Write-Host ('[ERROR] Failed to start {0}.' -f $ScriptPath)
            return $false
        }
        $Jobs += [pscustomobject]@{ Script = $ScriptPath; Process = $Process }
    }

    $Failed = $false
    foreach ($Job in $Jobs) {
        $Job.Process.WaitForExit()
        if ($Job.Process.ExitCode -ne 0) {
            Write-Host ('[ERROR] Failed: {0} (exit {1})' -f $Job.Script, $Job.Process.ExitCode)
            $Failed = $true
        }
        else {
            Write-Host ('[INFO] Completed: {0}' -f $Job.Script)
        }
    }
    return -not $Failed
}

function Stop-OtelCollector {
    param ([string]$DeployBaseDirectory)

    $OtelBinDir = Join-Path $DeployBaseDirectory 'otelcol\bin'
    if (-not (Test-Path -LiteralPath $OtelBinDir -PathType Container)) {
        Write-Host '[INFO] Otel collector not found, skipped.'
        return
    }

    $Processes = @(Get-Process -Name 'otelcol-contrib' -ErrorAction SilentlyContinue)
    if ($Processes.Count -eq 0) {
        Write-Host '[INFO] Otel collector not running, skipped.'
        return
    }

    foreach ($Process in $Processes) {
        Write-Host ('[INFO] Stopping otel collector (pid {0}).' -f $Process.Id)
        Stop-Process -Id $Process.Id -Force -ErrorAction SilentlyContinue
    }
    Write-Host '[INFO] Otel collector stopped.'
}

function Invoke-ServiceBatch {
    param (
        [string]$ActionLabel,
        [int]$Group,
        [string[]]$Entries
    )

    if ($Entries.Count -eq 0) {
        Write-Host ('[INFO] Batch {0} does not contain any entry, skipped.' -f $Group)
        return
    }

    $ScriptPaths = @()
    foreach ($Entry in $Entries) {
        $Parts = @($Entry -split ' ', 2)
        $ServiceName = $Parts[0]
        $BusAddr = $Parts[1]
        $ScriptPath = Join-Path (Join-Path $DeployBaseDirectory $ServiceName) ('bin\stop_{0}.ps1' -f $BusAddr)
        if (-not (Test-Path -LiteralPath $ScriptPath -PathType Leaf)) {
            Write-Host ('[ERROR] Missing stop script: "{0}"' -f $ScriptPath)
            exit 1
        }
        $ScriptPaths += $ScriptPath
    }

    Write-Host ('[INFO] Batch {0}: {1}' -f $Group, ($Entries -join ' '))
    if (-not (Invoke-ScriptsInParallel -ScriptPaths $ScriptPaths -ActionLabel $ActionLabel)) {
        exit 1
    }
}

if ($Help) {
    Show-Help
    exit 0
}

if (-not (Test-Path -LiteralPath $DeployBaseDirectory -PathType Container)) {
    Write-Host ('[ERROR] Deploy base directory does not exist: "{0}"' -f $DeployBaseDirectory)
    exit 1
}
$DeployBaseDirectory = (Resolve-Path -LiteralPath $DeployBaseDirectory).ProviderPath

{{ range $group := reverse .Values.proc_groups }}{{ $Entries := list }}{{ range $proc := $group.procs }}{{ range $instance := $proc.instances }}{{ $Entries = append $Entries (printf "%s %s" $proc.name $instance.bus_addr) }}{{ end }}{{ end }}
Invoke-ServiceBatch -ActionLabel 'Stopping' -Group {{ $group.group }} -Entries (ConvertFrom-Json '{{ $Entries | toJson }}')
{{ end }}

Stop-OtelCollector -DeployBaseDirectory $DeployBaseDirectory

Write-Host '[INFO] All batches completed successfully.'
exit 0