{{- template "libapp.configmap" (list . "cachesvr.configmap") -}}
{{- define "cachesvr.configmap" -}}
data:
  {{ include "cachesvr.name" . }}.yaml: {{ tpl (.Files.Get "cfg/cachesvr.yaml.tpl") . | quote }}
{{- end -}}
