// Copyright 2026 atframework

#include <atframework/testing/runtime.h>

#include <atframe/atapp.h>

#include <common/file_system.h>
#include <time/time_utility.h>

#include <config/logic_config.h>
#include <dispatcher/cs_msg_dispatcher.h>
#include <dispatcher/db_msg_dispatcher.h>
#include <dispatcher/ss_msg_dispatcher.h>
#include <dispatcher/task_manager.h>
#include <logic/logic_server_setup.h>
#include <testing/unit_test_reset.h>

#include <atframework/testing/mock_connector.h>
#include <atframework/testing/mock_cs.h>
#include <atframework/testing/mock_db.h>
#include <atframework/testing/mock_discovery.h>
#include <atframework/testing/mock_dns.h>
#include <atframework/testing/mock_hpa.h>
#include <atframework/testing/mock_resource.h>
#include <atframework/testing/mock_router.h>
#include <atframework/testing/mock_ss.h>
#include <atframework/testing/raw_transport.h>

#include <algorithm>
#include <atomic>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "rpc/rpc_async_invoke.h"

namespace {

static std::atomic<atframework::testing::runtime *> g_active_runtime{nullptr};

enum class runtime_state : int32_t {
  constructed = 0,
  starting,
  running,
  stopping,
  stopped,
};

static bool runtime_generate_config(const atframework::testing::runtime_options &options, std::string &output) {
  using atframework::testing::feature;
  bool use_session_manager = options.has_feature(feature::cs);
  bool use_excel_config = options.has_feature(feature::resource);

  std::stringstream ss;
  ss << "# Generated by atframework::testing::runtime, do not edit\n";
  ss << "atapp:\n";
  ss << "  id: 0x" << std::hex << options.app_id << std::dec << '\n';
  ss << "  id_mask: 8.8.8.8\n";
  ss << "  name: \"" << options.app_name << "\"\n";
  ss << "  type_id: " << options.type_id << '\n';
  ss << "  type_name: \"" << options.type_name << "\"\n";
  ss << "  bus:\n";
  // Empty listen: bus node exists but no real endpoint is bound (offline guarantee).
  ss << "    listen: []\n";
  ss << "    proxy: \"\"\n";
  ss << "    backlog: 256\n";
  ss << "    first_idle_timeout: 10s\n";
  ss << "    ping_interval: 60s\n";
  ss << "    retry_interval: 3s\n";
  ss << "    fault_tolerant: 3\n";
  ss << "    message_size: 64KB\n";
  ss << "    receive_buffer_size: 1MB\n";
  ss << "    send_buffer_size: 1MB\n";
  ss << "    send_buffer_number: 0\n";
  ss << "  timer:\n";
  ss << "    tick_interval: 8ms\n";
  // Short and non-zero stop timeout/interval so teardown never waits for the default long timeout.
  ss << "    stop_timeout: 2s\n";
  ss << "    stop_interval: 128ms\n";
  ss << "  etcd:\n";
  ss << "    enable: false\n";
  ss << "  log:\n";
  ss << "    level: warning\n";
  ss << "    category:\n";
  ss << "      - name: default\n";
  ss << "        prefix: \"[Log %L][%F %T.%f][%s:%n(%C)]: \"\n";
  ss << "        sink:\n";
  ss << "          - type: stderr\n";
  ss << "            level:\n";
  ss << "              min: fatal\n";
  ss << "              max: warning\n";
  ss << "logic:\n";
  ss << "  world_id: " << options.world_id << '\n';
  ss << "  zone_id: " << options.zone_id << '\n';
  ss << "  logic_id: 1\n";
  ss << "  server:\n";
  ss << "    shared_component:\n";
  ss << "      task_manager: true\n";
  ss << "      router_manager_set: " << (options.has_feature(feature::router) ? "true" : "false") << '\n';
  ss << "      session_manager: " << (use_session_manager ? "true" : "false") << '\n';
  ss << "      excel_config: " << (use_excel_config ? "true" : "false") << '\n';
  ss << "  excel:\n";
  ss << "    enable: " << (use_excel_config ? "true" : "false") << '\n';
  ss << "  dns:\n";
  ss << "    lookup_timeout: 5s\n";

  // Telemetry (8.9): default is a full noop (no exporters, zero network). File-only exporters and the HPA
  // prometheus pull source are materialized here; forbidden exporters are rejected in start() before this.
  bool has_hpa = options.has_feature(feature::hpa);
  bool use_otlp_file = !options.telemetry_otlp_file_pattern.empty();
  if (use_otlp_file || options.telemetry_ostream_stderr || has_hpa) {
    ss << "  telemetry:\n";
    if (use_otlp_file || options.telemetry_ostream_stderr) {
      ss << "    opentelemetry:\n";
      ss << "      trace:\n";
      ss << "        exporters:\n";
      if (use_otlp_file) {
        ss << "          otlp_file:\n";
        ss << "            file_pattern: \"" << options.telemetry_otlp_file_pattern << ".trace.log\"\n";
        // Small flush knobs so short-lived unit tests see the file promptly instead of waiting for the
        // default 256-record batch.
        ss << "            flush_interval: 1s\n";
        ss << "            flush_count: 1\n";
      }
      if (options.telemetry_ostream_stderr) {
        ss << "          ostream: \"stderr\"\n";
      }
      // Trace provider requires both exporters and processors (8.9).
      ss << "        processors:\n";
      ss << "          simple: {}\n";
      ss << "      metrics:\n";
      ss << "        exporters:\n";
      if (use_otlp_file) {
        ss << "          otlp_file:\n";
        ss << "            file_pattern: \"" << options.telemetry_otlp_file_pattern << ".metrics.log\"\n";
      }
      if (options.telemetry_ostream_stderr) {
        ss << "          ostream: \"stderr\"\n";
      }
      ss << "      logs:\n";
      ss << "        exporters:\n";
      if (use_otlp_file) {
        ss << "          otlp_file:\n";
        ss << "            file_pattern: \"" << options.telemetry_otlp_file_pattern << ".logs.log\"\n";
      }
      if (options.telemetry_ostream_stderr) {
        ss << "          ostream: \"stderr\"\n";
      }
    }
    if (has_hpa) {
      // The HPA pull URL source lives in the metrics configure of the "hpa" telemetry group. The URL is
      // unreachable on purpose: with the hpa feature the runtime installs the mock pull hook, so no real
      // HTTP request is ever created (8.10).
      ss << "    group:\n";
      ss << "      - name: \"hpa\"\n";
      ss << "        configure:\n";
      ss << "          metrics:\n";
      ss << "            exporters:\n";
      ss << "              prometheus_http_api:\n";
      ss << "                url: \"http://127.0.0.1:19090\"\n";
    }
  }
  if (has_hpa) {
    ss << "  hpa:\n";
    ss << "    controller:\n";
    ss << "      enable: true\n";
    // configure_key stays empty: no etcd discovery in unit tests (8.10).
    ss << "    metrics:\n";
    ss << "      enable: true\n";
    ss << "      pull_interval: 1s\n";
    ss << "      pull_retry_interval: 1s\n";
    ss << "    rule:\n";
    ss << "      custom:\n";
    ss << "        - metrics_name: \"rpc_unit_test_custom\"\n";
    ss << "          metrics_type: gauge\n";
  }

  output = ss.str();
  return true;
}

}  // namespace

namespace atframework {
namespace testing {

struct runtime::impl_data {
  runtime_state state = runtime_state::constructed;
  runtime_options options;
  std::unique_ptr<atfw::atapp::app> app;
  std::string config_file_path;
  bool poisoned = false;
  std::string diagnostic;
  uint64_t pump_generation = 0;

  mock_discovery discovery_engine;
  raw_transport transport_engine;
  mock_ss ss_engine;
  mock_router router_engine;
  mock_dns dns_engine;
  mock_db db_engine;
  mock_resource resource_engine;
  mock_hpa hpa_engine;
  mock_cs cs_engine;
  std::shared_ptr<mock_connector> connector;
};

bool runtime_options::has_feature(feature input) const noexcept {
  return std::find(features.begin(), features.end(), input) != features.end();
}

bool task_handle::empty() const noexcept { return !started_ || task_type_trait::empty(task_); }

uint64_t task_handle::get_task_id() const noexcept {
  if (!started_) {
    return 0;
  }
  return static_cast<uint64_t>(task_type_trait::get_task_id(task_));
}

runtime::runtime() : impl_(std::make_unique<impl_data>()) {}

runtime::~runtime() {
  if (impl_ && (impl_->state == runtime_state::running || impl_->state == runtime_state::starting)) {
    stop();
  }
  runtime *expected = this;
  g_active_runtime.compare_exchange_strong(expected, nullptr);
}

int runtime::start(const runtime_options &options) {
  if (!impl_) {
    impl_ = std::make_unique<impl_data>();
  }
  impl_->diagnostic.clear();
  if (impl_->state == runtime_state::running || impl_->state == runtime_state::starting) {
    impl_->diagnostic = "runtime is already running";
    return -1;
  }

  runtime *expected = nullptr;
  if (!g_active_runtime.compare_exchange_strong(expected, this)) {
    impl_->diagnostic = "another atframework::testing::runtime is active in this process";
    return -1;
  }

  impl_->options = options;
  impl_->state = runtime_state::starting;
  impl_->pump_generation = 0;

  // Fail fast on forbidden telemetry exporters (8.9): outbound connections and inbound listeners are never
  // allowed in unit tests; use telemetry_otlp_file_pattern or telemetry_ostream_stderr instead.
  do {
    std::string forbidden;
    if (!options.telemetry_otlp_grpc_endpoint.empty()) {
      forbidden = "telemetry_otlp_grpc_endpoint";
    } else if (!options.telemetry_otlp_http_endpoint.empty()) {
      forbidden = "telemetry_otlp_http_endpoint";
    } else if (!options.telemetry_prometheus_push_host.empty()) {
      forbidden = "telemetry_prometheus_push_host";
    } else if (!options.telemetry_prometheus_pull_url.empty()) {
      forbidden = "telemetry_prometheus_pull_url";
    }
    if (!forbidden.empty()) {
      impl_->diagnostic = "forbidden telemetry exporter option in unit tests: " + forbidden +
                          " (use telemetry_otlp_file_pattern or telemetry_ostream_stderr)";
      impl_->state = runtime_state::constructed;
      runtime *expected_self = this;
      g_active_runtime.compare_exchange_strong(expected_self, nullptr);
      return -1;
    }
  } while (false);

  // Rollback helper: tear down whatever has been set up and release the active-runtime guard.
  auto rollback = [this](int error_code) {
    if (impl_->app) {
      task_manager::me()->kill_all();
      if (impl_->app->is_running()) {
        impl_->app->stop();
        auto deadline = atfw::util::time::time_utility::sys_now() + impl_->options.teardown_deadline;
        while (!impl_->app->is_closed() && atfw::util::time::time_utility::sys_now() < deadline) {
          atfw::util::time::time_utility::update();
          impl_->app->run_noblock();
          std::this_thread::yield();
        }
      }
      impl_->app.reset();
    }
    impl_->transport_engine.unbind();
    impl_->discovery_engine.unbind();
    impl_->ss_engine.unbind();
    impl_->router_engine.unbind();
    impl_->dns_engine.unbind();
    impl_->db_engine.unbind();
    impl_->resource_engine.unbind();
    impl_->hpa_engine.unbind();
    impl_->cs_engine.unbind();
    impl_->connector.reset();
#if defined(PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS) && PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS
    server_frame_unit_test_reset_dispatcher_registrations();
#endif
    impl_->state = runtime_state::constructed;
    runtime *expected_self = this;
    g_active_runtime.compare_exchange_strong(expected_self, nullptr);
    return error_code;
  };

  // Working directory and config file
  do {
    std::string workdir = options.working_directory;
    if (workdir.empty()) {
      // ctest sets RPC_UNIT_TEST_WORKDIR per target (preserves per-target isolation); a directly-invoked
      // executable has no such env, so fall back to the build-tree default baked by the CMake helper
      // (RPC_UNIT_TEST_DEFAULT_WORKDIR) instead of the current working directory, which may be the
      // repository root and would pollute it with the generated config file.
      std::string env_workdir = atfw::util::file_system::getenv("RPC_UNIT_TEST_WORKDIR");
      if (!env_workdir.empty()) {
        workdir = env_workdir;
      } else {
#if defined(RPC_UNIT_TEST_DEFAULT_WORKDIR)
        workdir = RPC_UNIT_TEST_DEFAULT_WORKDIR;
#endif
      }
    }
    if (workdir.empty()) {
      workdir = atfw::util::file_system::get_cwd();
    }
    if (!atfw::util::file_system::is_exist(workdir.c_str())) {
      atfw::util::file_system::mkdir(workdir.c_str(), true);
    }

    std::string config_content;
    runtime_generate_config(options, config_content);

    impl_->config_file_path = workdir + "/rpc-unit-test.yaml";
    std::string old_content;
    {
      std::ifstream old_file(impl_->config_file_path.c_str(), std::ios::in | std::ios::binary);
      if (old_file) {
        std::stringstream buffer;
        buffer << old_file.rdbuf();
        old_content = buffer.str();
      }
    }
    if (old_content != config_content) {
      std::ofstream config_file(impl_->config_file_path.c_str(), std::ios::out | std::ios::binary | std::ios::trunc);
      if (!config_file) {
        impl_->diagnostic = "can not write config file: " + impl_->config_file_path;
        return rollback(-1);
      }
      config_file << config_content;
    }
  } while (false);

  impl_->app = std::make_unique<atfw::atapp::app>();

  // Bind mock engines before init so endpoints created later pick up the mock connector.
  impl_->transport_engine.bind(impl_->app.get());
  impl_->discovery_engine.bind(impl_->app.get());
  if (options.has_feature(feature::ss) || options.has_feature(feature::router)) {
    impl_->ss_engine.bind(impl_->app.get(), impl_->transport_engine);
    impl_->connector = impl_->app->add_connector<mock_connector>(impl_->transport_engine);
    if (!impl_->connector) {
      impl_->diagnostic = "add mock connector failed";
      return rollback(-1);
    }
  }
  if (options.has_feature(feature::dns)) {
    impl_->dns_engine.bind();
  }
  if (options.has_feature(feature::db)) {
    if (!db_msg_dispatcher::me()->set_record_info_for_unit_test("unit-test",
                                                                db_msg_dispatcher::channel_t::RAW_DEFAULT)) {
      impl_->diagnostic = "set db record info for unit test failed";
      return rollback(-1);
    }
    impl_->db_engine.bind();
  }
  if (options.has_feature(feature::resource)) {
    impl_->resource_engine.bind();
  }
  if (options.has_feature(feature::hpa)) {
    impl_->hpa_engine.bind();
  }
  if (options.has_feature(feature::cs)) {
    impl_->cs_engine.bind();
  }

#if defined(PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS) && PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS
  // Defensive: a previous fixture may have aborted without stop() and left registered handles in the
  // process-lifetime dispatcher singletons.
  server_frame_unit_test_reset_dispatcher_registrations();
#endif

  logic_server_common_module_configure logic_mod_conf;
  if (logic_server_setup_common(*impl_->app, logic_mod_conf) < 0) {
    impl_->diagnostic = "logic_server_setup_common failed";
    return rollback(-1);
  }

  if (options.has_feature(feature::ss) || options.has_feature(feature::dns) || options.has_feature(feature::router)) {
    // Dispatcher singletons outlive one fixture: atapp disables modules on stop, so re-enable them
    // before adding, otherwise app->init skips their init() and their state (e.g. is_closing_)
    // leaks into the next fixture.
    ss_msg_dispatcher::me()->reenable_for_unit_test();
    impl_->app->add_module(ss_msg_dispatcher::me());
  }
  if (options.has_feature(feature::cs)) {
    cs_msg_dispatcher::me()->reenable_for_unit_test();
    impl_->app->add_module(cs_msg_dispatcher::me());
  }
  // NOTE: db_msg_dispatcher is never added here. The default in-memory DB does not need it and adding
  // it would require init(), which connects to real Redis.

  if (options.setup_callback) {
    int callback_result = options.setup_callback(*this);
    if (callback_result != 0) {
      impl_->diagnostic = "setup_callback failed with " + std::to_string(callback_result);
      return rollback(callback_result);
    }
  }

  {
    std::vector<std::string> args_storage = {options.app_name, "-c", impl_->config_file_path, "start"};
    std::vector<const char *> args;
    args.reserve(args_storage.size());
    for (const auto &arg : args_storage) {
      args.push_back(arg.c_str());
    }

    int init_result = impl_->app->init(nullptr, static_cast<int>(args.size()), args.data(), nullptr);
    if (init_result != 0) {
      impl_->diagnostic = "app.init failed with " + std::to_string(init_result);
      return rollback(init_result);
    }
  }

  // Preheat pump: let modules finish init/ready and settle pending events.
  for (int i = 0; i < 64; ++i) {
    atfw::util::time::time_utility::update();
    int pump_result = impl_->app->run_noblock();
    if (pump_result < 0) {
      impl_->diagnostic = "app.run_noblock failed with " + std::to_string(pump_result) + " during preheat";
      return rollback(pump_result);
    }
    if (0 == pump_result) {
      break;
    }
  }

  impl_->state = runtime_state::running;
  return 0;
}

int runtime::stop() noexcept {
  if (!impl_) {
    runtime *expected = this;
    g_active_runtime.compare_exchange_strong(expected, nullptr);
    return 0;
  }
  if (impl_->state == runtime_state::constructed || impl_->state == runtime_state::stopped) {
    impl_->state = runtime_state::stopped;
    runtime *expected = this;
    g_active_runtime.compare_exchange_strong(expected, nullptr);
    return 0;
  }

  int ret = 0;
  impl_->state = runtime_state::stopping;

  if (impl_->app) {
    // Kill all remaining tasks first; there is no safe per-task kill API.
    task_manager::me()->kill_all();

    // Verify SS expectations and unconsumed rules before dropping any state.
    {
      std::string expectation_diagnostic;
      if (!impl_->ss_engine.verify_expectations(expectation_diagnostic)) {
        if (!impl_->diagnostic.empty()) {
          impl_->diagnostic += "; ";
        }
        impl_->diagnostic += expectation_diagnostic;
        ret = 2;
      }
      size_t unconsumed = impl_->ss_engine.unconsumed_rule_count();
      if (unconsumed > 0) {
        if (!impl_->diagnostic.empty()) {
          impl_->diagnostic += "; ";
        }
        impl_->diagnostic += std::to_string(unconsumed) + " ss rule(s) never fired";
        ret = 2;
      }
    }

    // Block new mock requests, drop pending deliveries and remove injected discovery nodes before
    // the app stop flow starts.
    impl_->transport_engine.unbind();
    impl_->discovery_engine.unbind();
    impl_->ss_engine.unbind();
    impl_->router_engine.unbind();
    impl_->dns_engine.unbind();
    impl_->db_engine.unbind();
    impl_->resource_engine.unbind();
    impl_->hpa_engine.unbind();
    impl_->cs_engine.unbind();

    impl_->app->stop();

    auto deadline = atfw::util::time::time_utility::sys_now() + impl_->options.teardown_deadline;
    while (!impl_->app->is_closed()) {
      atfw::util::time::time_utility::update();
      impl_->app->run_noblock();
      if (atfw::util::time::time_utility::sys_now() >= deadline) {
        // Trigger module timeout path instead of waiting for the default long stop timeout.
        task_manager::me()->kill_all();
        impl_->diagnostic = "teardown deadline exceeded";
        ret = 1;
        break;
      }
      std::this_thread::yield();
    }

    impl_->app.reset();
    impl_->connector.reset();
  }

#if defined(PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS) && PROJECT_SERVER_FRAME_ENABLE_UNIT_TEST_HOOKS
  server_frame_unit_test_reset_dispatcher_registrations();
#endif

  impl_->state = runtime_state::stopped;
  runtime *expected = this;
  g_active_runtime.compare_exchange_strong(expected, nullptr);
  return ret;
}

bool runtime::is_running() const noexcept { return impl_ && impl_->state == runtime_state::running; }

bool runtime::is_poisoned() const noexcept { return impl_ && impl_->poisoned; }

const std::string &runtime::get_diagnostic() const noexcept {
  static const std::string empty_string;
  if (!impl_) {
    return empty_string;
  }
  return impl_->diagnostic;
}

task_handle runtime::run_task(gsl::string_view name, std::chrono::system_clock::duration timeout,
                              std::function<rpc::result_code_type(rpc::context &)> fn) {
  task_handle ret;
  if (!impl_ || impl_->state != runtime_state::running) {
    ret.diagnostic_ = "runtime is not running";
    return ret;
  }
  if (impl_->poisoned) {
    ret.diagnostic_ = "runtime is poisoned, only stop() is allowed";
    return ret;
  }

  rpc::async_invoke_result invoke_result =
      rpc::async_invoke("atframework::testing::runtime", name, std::move(fn), timeout);
  if (!invoke_result.is_success()) {
    auto error = invoke_result.get_error();
    ret.diagnostic_ = "rpc::async_invoke failed";
    if (error) {
      ret.diagnostic_ += " with " + std::to_string(*error);
    }
    return ret;
  }

  auto task_ptr = invoke_result.get_success();
  if (!task_ptr) {
    ret.diagnostic_ = "rpc::async_invoke returns empty task";
    return ret;
  }
  ret.task_ = *task_ptr;
  ret.started_ = true;
  return ret;
}

wait_result runtime::wait(const task_handle &task, std::chrono::system_clock::duration hard_timeout) {
  wait_result ret;
  auto begin_timepoint = atfw::util::time::time_utility::sys_now();

  if (!task.started_) {
    ret.diagnostic = task.get_diagnostic().empty() ? "task was not started" : task.get_diagnostic();
    return ret;
  }
  ret.task_started = true;
  ret.task_id = task.get_task_id();

  if (!impl_ || impl_->state != runtime_state::running) {
    ret.diagnostic = "runtime is not running";
    return ret;
  }
  if (impl_->poisoned) {
    ret.runtime_poisoned = true;
    ret.diagnostic = "runtime is poisoned, only stop() is allowed";
    return ret;
  }

  auto deadline = begin_timepoint + hard_timeout;
  while (true) {
    pump_once();

    if (task_type_trait::empty(task.task_) || task_type_trait::is_exiting(task.task_)) {
      ret.task_exited = true;
      ret.task_timed_out = task_type_trait::is_timeout(task.task_);
      ret.task_canceled = task_type_trait::is_cancel(task.task_);
      ret.task_faulted = task_type_trait::is_fault(task.task_);
      ret.result_code = task_type_trait::get_result(task.task_);
      break;
    }

    if (atfw::util::time::time_utility::sys_now() >= deadline) {
      ret.hard_timed_out = true;
      ret.runtime_poisoned = true;
      ret.diagnostic = "runtime hard timeout, all tasks are killed and the runtime is poisoned";
      impl_->poisoned = true;
      task_manager::me()->kill_all();
      break;
    }

    std::this_thread::yield();
  }

  ret.elapsed = atfw::util::time::time_utility::sys_now() - begin_timepoint;
  if (impl_) {
    ret.runtime_poisoned = ret.runtime_poisoned || impl_->poisoned;
  }
  return ret;
}

int runtime::pump_once() noexcept {
  if (!impl_ || !impl_->app) {
    return -1;
  }

  atfw::util::time::time_utility::update();
  int ret = impl_->app->run_noblock();
  if (ret < 0) {
    impl_->poisoned = true;
    return ret;
  }
  ++impl_->pump_generation;

  // Deliver due mock events of older generations here (SS/DNS/CS/etc. engines register into the
  // pending queue), then run the loop again so the real dispatchers resume tasks.
  impl_->transport_engine.set_current_generation(impl_->pump_generation);
  impl_->transport_engine.deliver_pending();
  impl_->ss_engine.deliver_pending();
  impl_->dns_engine.deliver_pending();

  ret = impl_->app->run_noblock();
  if (ret < 0) {
    impl_->poisoned = true;
  }
  return ret;
}

atfw::atapp::app *runtime::get_app() const noexcept {
  if (!impl_) {
    return nullptr;
  }
  return impl_->app.get();
}

mock_discovery &runtime::discovery() noexcept { return impl_->discovery_engine; }

raw_transport &runtime::transport() noexcept { return impl_->transport_engine; }

mock_ss &runtime::ss() noexcept { return impl_->ss_engine; }

mock_router &runtime::router() noexcept { return impl_->router_engine; }

mock_dns &runtime::dns() noexcept { return impl_->dns_engine; }

mock_db &runtime::db() noexcept { return impl_->db_engine; }

mock_resource &runtime::resource() noexcept { return impl_->resource_engine; }

mock_hpa &runtime::hpa() noexcept { return impl_->hpa_engine; }

mock_cs &runtime::cs() noexcept { return impl_->cs_engine; }

}  // namespace testing
}  // namespace atframework
