# =========== server_frame ===========
set(PROJECT_SERVER_FRAME_BAS_DIR ${CMAKE_CURRENT_LIST_DIR})
set(PROJECT_SERVER_FRAME_INC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set(PROJECT_SERVER_FRAME_SRC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set(PROJECT_SERVER_FRAME_PROTOCOL_DIR "${PROJECT_SERVER_FRAME_BAS_DIR}/protocol")
set(PROJECT_SERVER_FRAME_LIB_LINK server_frame)

set(PROJECT_SERVER_FRAME_NAMESPACE "hello")
string(REPLACE "." "::" PROJECT_SERVER_FRAME_NAMESPACE_ID "${PROJECT_SERVER_FRAME_NAMESPACE}")
string(REGEX MATCHALL "[A-Za-z0-9_]+"
PROJECT_SERVER_FRAME_NAMESPACE_IDENTS "${PROJECT_SERVER_FRAME_NAMESPACE_ID}")
unset(PROJECT_SERVER_FRAME_NAMESPACE_BEGIN)
unset(PROJECT_SERVER_FRAME_NAMESPACE_END)
foreach(NAMESPACE_IDENT IN LISTS PROJECT_SERVER_FRAME_NAMESPACE_IDENTS)
  set(PROJECT_SERVER_FRAME_NAMESPACE_BEGIN "${PROJECT_SERVER_FRAME_NAMESPACE_BEGIN}namespace ${NAMESPACE_IDENT} { \\\n")
  set(PROJECT_SERVER_FRAME_NAMESPACE_END "${PROJECT_SERVER_FRAME_NAMESPACE_END}} \\\n")
endforeach()
set(PROJECT_SERVER_FRAME_NAMESPACE_BEGIN "${PROJECT_SERVER_FRAME_NAMESPACE_BEGIN}// namespace begin for ${PROJECT_SERVER_FRAME_NAMESPACE_ID}\n")
set(PROJECT_SERVER_FRAME_NAMESPACE_END "${PROJECT_SERVER_FRAME_NAMESPACE_END}// namespace end for ${PROJECT_SERVER_FRAME_NAMESPACE_ID}\n")
