# =========== server_frame ===========
set(PROJECT_SERVER_FRAME_BAS_DIR ${CMAKE_CURRENT_LIST_DIR})
set(PROJECT_SERVER_FRAME_INC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set(PROJECT_SERVER_FRAME_SRC_DIR ${PROJECT_SERVER_FRAME_BAS_DIR})
set(PROJECT_SERVER_FRAME_LIB_LINK server_frame)
set(PROJECT_SERVER_FRAME_PROTOCOL_DIR "${PROJECT_SERVER_FRAME_BAS_DIR}/protocol")
set(PROJECT_SERVER_FRAME_PROTOCOL_SOURCE_DIR "${PROJECT_GENERATED_DIR}/${PROJECT_SERVER_FRAME_LIB_LINK}-protocol")

# Sandbox directories
set(PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR "${PROJECT_SANDBOX_ROOT_DIR}/protocol")
set(PROJECT_SERVER_FRAME_PROTO_SANDBOX_EXTENSION_DIR "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}/extension")
set(PROJECT_SERVER_FRAME_PROTO_SANDBOX_COMMON_DIR "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}/common")
set(PROJECT_SERVER_FRAME_PROTO_SANDBOX_CONFIG_DIR "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}/config")
set(PROJECT_SERVER_FRAME_PROTO_SANDBOX_PBDESC_DIR "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}/pbdesc")
if(EXISTS "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}")
  file(REMOVE_RECURSE "${PROJECT_SERVER_FRAME_PROTO_SANDBOX_DIR}")
endif()

set(PROJECT_NAMESPACE "hello")
string(REPLACE "." "::" PROJECT_NAMESPACE_ID "${PROJECT_NAMESPACE}")
string(REGEX MATCHALL "[A-Za-z0-9_]+" PROJECT_SERVER_FRAME_NAMESPACE_IDENTS "${PROJECT_NAMESPACE_ID}")
unset(PROJECT_NAMESPACE_BEGIN)
unset(PROJECT_NAMESPACE_END)
foreach(NAMESPACE_IDENT IN LISTS PROJECT_SERVER_FRAME_NAMESPACE_IDENTS)
  set(PROJECT_NAMESPACE_BEGIN "${PROJECT_NAMESPACE_BEGIN}namespace ${NAMESPACE_IDENT} { \\\n")
  set(PROJECT_NAMESPACE_END "${PROJECT_NAMESPACE_END}} \\\n")
endforeach()
set(PROJECT_NAMESPACE_BEGIN "${PROJECT_NAMESPACE_BEGIN}// namespace begin for ${PROJECT_NAMESPACE_ID}\n")
set(PROJECT_NAMESPACE_END "${PROJECT_NAMESPACE_END}// namespace end for ${PROJECT_NAMESPACE_ID}\n")

# Protobuf proto directory
if(VCPKG_INSTALLED_DIR
   AND VCPKG_TARGET_TRIPLET
   AND EXISTS "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include/google/protobuf/descriptor.proto")
  set(PROJECT_THIRD_PARTY_PROTOBUF_PROTO_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
else()
  set(PROJECT_THIRD_PARTY_PROTOBUF_PROTO_DIR "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include")
endif()
