# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: orbit-serverd

type_id: 25
type_name: "orbit-server"

image:
  repository: harbor.atframe.work/atsf4g-co/server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/orbit-server/cfg
  logMountPath: /data/atframework/publish/orbit-server/log

vector:
  enabled: false
  log_path: /data/atframework/publish/orbit-server/log