syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/pbdesc/com.struct.proto";

package atframework.shared;

// 注意和DtMq.xlsx 表对应，多个模块之间类型不要冲突
enum EnOrbitChannelType {
  EN_ORBIT_CHANNEL_TYPE_INVALID = 0;
  EN_ORBIT_CHANNEL_TYPE_ROOM = 101;
}

message DOrbitRoomKey {
  string client_id = 1;
}

message DOrbitUserKey {
  DUserIDKey user_key = 1;
  string orbit_user_key = 2;
}

enum EnOrbitUserStatusType {
  EN_ORBIT_USER_STATUS_TYPE_UNKNOW = 0;
}

message DOrbitUserInitDataDetail {
  // 用户初始化数据
}

message DOrbitUserFinishResultDetail {
  // 用户完成数据
}

message DOrbitUserFinishAsyncData {
  DOrbitRoomKey room_key = 1;
  int64 start_timepoint = 2;
  int64 finish_timepoint = 3;
  DOrbitRoomExitInfo exit_info = 4;
  bool init_success = 5;
  repeated DOrbitUserInitData user_init_datas = 11;          // 参与用户
  repeated DOrbitUserFinishResult user_finish_results = 12;  // 参与用户完成结果
}

message DOrbitUserInitData {
  DOrbitUserKey user_key = 1;
  int32 faction_id = 2;
  DOrbitUserInitDataDetail data = 3;
}

message DOrbitUserInitResult {
  DOrbitUserKey user_key = 1;
  string token = 2;
}

message DOrbitUserFinishResult {
  DOrbitUserKey user_key = 1;
  int32 index = 2;
  EnOrbitUserStatusType status = 3;
  DOrbitUserFinishResultDetail data = 4;
}

message DOrbitRoomInitData {
  uint32 client_template_id = 1;
  string region = 2;
  string match_id = 3;
}

enum EnOrbitRoomStatus {
  EN_ORBIT_ROOM_STATUS_INVALID = 0;         // 无效值
  EN_ORBIT_ROOM_STATUS_CREATED = 1;         // 房间创建成功
  EN_ORBIT_ROOM_STATUS_CLIENT_LOADING = 2;  // 加载中
  EN_ORBIT_ROOM_STATUS_CLIENT_RUNNING = 3;  // 运行中
  EN_ORBIT_ROOM_STATUS_FINISH = 4;          // 结束
  EN_ORBIT_ROOM_STATUS_EXIT = 5;            // 退出
}

enum EnOrbitRoomExitReason {
  EN_ORBIT_ROOM_EXIT_REASON_UNKNOWN = 0;
  EN_ORBIT_ROOM_EXIT_REASON_LOAD_FAILED = 1;          // 分配失败
  EN_ORBIT_ROOM_EXIT_REASON_NOTIFY_MATCH_FAILED = 2;  // 通知匹配服务器失败
  EN_ORBIT_ROOM_EXIT_REASON_USER_INIT_FAILED = 3;     // 用户初始化失败
  EN_ORBIT_ROOM_EXIT_REASON_CRASH = 4;                // 崩溃
  EN_ORBIT_ROOM_EXIT_REASON_TIMEOUT = 5;              // 超时
  EN_ORBIT_ROOM_EXIT_REASON_FINISH = 6;               // 正常结束
}

// ====== WAL 事件体 ======

message DOrbitRoomExitInfo {
  EnOrbitRoomExitReason exit_reason = 1;
}

message DOrbitRoomInit {
  uint32 client_template_id = 1;
  string region = 2;
  string match_id = 3;
  int64 create_timepoint = 4;
  int64 expired_timepoint = 5;
}

message DOrbitRoomReady {
  int64 end_join_timepoint = 1;
  string client_address = 2;
}

message DOrbitUserInit {
  DOrbitUserInitResult init_result = 1;
}

message DOrbitUserFinish {
  DUserIDKey user_key = 1;
}

message DOrbitClientExit {
  DOrbitRoomExitInfo exit_info = 1;
}

message DOrbitRoomEventLog {
  EnOrbitRoomStatus orbit_room_status = 1;  // 战斗房间状态
  DOrbitRoomKey room_key = 2;               // 房间key

  oneof event {
    DOrbitRoomInit room_init = 100;          // 房间创建
    DOrbitRoomReady ready_data = 101;        // 房间准备就绪
    DOrbitUserInit user_init_success = 102;  // 用户初始化成功
    DOrbitClientExit client_exit = 103;      // Client退出
  }
}

message DOrbitRoomUserData {
  DOrbitRoomKey room_key = 1;  // 房间key
  string client_address = 2;   // Client地址
  bool init = 3;               // 是否已经初始化成功
  string token = 4;            // Client token
  uint32 client_template_id = 5;
  string region = 6;
  int64 create_timepoint = 7;
}

message DOrbitRoomDirty {
  DOrbitRoomUserData data = 1;
}