syntax = "proto3";

option optimize_for = SPEED;
option cc_enable_arenas = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/pbdesc/com.struct.team.proto";
import "protocol/pbdesc/com.struct.proto";

package atframework.team;

// Placeholder definitions for team protocol messages referenced by com.protocol.proto.
// These exist so proto generation succeeds; real definitions should be added here.

message CSTeamSendInvitationReq {}

message SCTeamSendInvitationRsp {}

message CSTeamApproveInvitationReq {}

message SCTeamApproveInvitationRsp {}

message CSTeamRejectInvitationReq {}

message SCTeamRejectInvitationRsp {}

message CSTeamExitReq {}

message SCTeamExitRsp {}

message CSTeamRemoveMemberReq {}

message SCTeamRemoveMemberRsp {}

message CSTeamSetReadyReq {}

message SCTeamSetReadyRsp {}

message CSTeamSetUnreadyReq {}

message SCTeamSetUnreadyRsp {}

message CSTeamApplyJoinTeamReq {}

message SCTeamApplyJoinTeamRsp {}

message CSTeamAcceptApplyReq {}

message SCTeamAcceptApplyRsp {}

message CSTeamRejectApplyReq {}

message SCTeamRejectApplyRsp {}

message CSTeamTransferCaptainReq {}

message SCTeamTransferCaptainRsp {}
