syntax = "proto3";
// 前后台通信协议定义

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

import "protocol/pbdesc/com.const.proto";
import "protocol/pbdesc/com.struct.proto";
import "protocol/pbdesc/com.protocol.rank.proto";
import "protocol/pbdesc/com.protocol.cache.proto";
import "protocol/pbdesc/com.protocol.chat.proto";
import "protocol/pbdesc/com.protocol.lobby.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

package atframework.shared;

/////////////////////////////////////////////////////
// 到loginsvr的CS协议
/////////////////////////////////////////////////////

message CSLoginUpdateReq {
  DAccountData account = 1;      // 平台信息
  EnSystemID system_id = 2;      // 系统id，ios or android
  string package_version = 11;   // 包版本
  string resource_version = 12;  // 资源版本
  string protocol_version = 13;  // 协议版本
}

message SCLoginUpdateRsp {
  DClientUpdateCfg update_info = 1;  // 更新信息
  int32 version_type = 2;            // 版本类型 @EnVersionType
}

message CSLoginAuthReq {
  string open_id = 1;
  DAccountData account = 2;      // 平台信息
  EnSystemID system_id = 3;      // 系统id，ios or android
  string package_version = 11;   // 包版本
  string resource_version = 12;  // 资源版本
  string protocol_version = 13;  // 协议版本

  DClientDeviceInfo client_info = 21;
}

message SCLoginAuthRsp {
  string access_token_code = 11;  // 认证码

  DClientUpdateCfg update_info = 3;  // 更新信息
  uint32 version_type = 4;           // 版本类型 @EnVersionType

  string open_id = 21;  // 最终open_id
  uint64 user_id = 22;  // 玩家数字ID

  int64 ban_time = 101;    // 封号期限
  int64 start_time = 102;  // 开服时间
}

service AuthsvrClientService {
  rpc login_auth(CSLoginAuthReq) returns (SCLoginAuthRsp) {
    option (atframework.rpc_options) = {
      api_name: "Authorization"
    };
  };
}

service LobbysvrClientService {
  rpc login(CSLoginReq) returns (SCLoginRsp) {
    option (atframework.rpc_options) = {
      api_name: "Login"
    };
  };

  rpc ping(CSPingReq) returns (SCPongRsp) {
    option (atframework.rpc_options) = {
      api_name: "Ping/pong"
    };
  };

  rpc access_update(CSAccessUpdateReq) returns (SCAccessUpdateRsp) {
    option (atframework.rpc_options) = {
      api_name: "Update access token"
    };
  };

  rpc player_get_info(CSPlayerGetInfoReq) returns (SCPlayerGetInfoRsp) {
    option (atframework.rpc_options) = {
      module_name: "player"
      api_name: "Get player data"
    };
  };

  // Use stream request to disable waiting for response
  rpc player_dirty_chg_sync(google.protobuf.Empty) returns (stream SCPlayerDirtyChgSync) {
    option (atframework.rpc_options) = {
      module_name: "player"
      api_name: "Push dirty data"
    };
  };

  // ================ 排行榜RPC ================
  rpc rank_get_specify_rank(CSRankGetSpecifyRankReq) returns (SCRankGetSpecifyRankRsp) {
    option (atframework.rpc_options) = {
      module_name: "rank"
      api_name: "获取指定排名范围的排行榜"
    };
  };

  rpc rank_get_self_rank(CSRankGetSelfRankReq) returns (SCRankGetSelfRankRsp) {
    option (atframework.rpc_options) = {
      module_name: "rank"
      api_name: "获取排行榜中自身及前后排名"
    };
  };

  rpc rank_cache_expired_sync(google.protobuf.Empty) returns (stream SCRankCacheExpiredSync) {
    option (atframework.rpc_options) = {
      module_name: "rank"
      api_name: "排行榜缓存失效通知"
    };
  };

  // ================ CACHE RPC =================
  // 批量拉取数据（并订阅）
  rpc cache_api_batch_get(CSCacheApiBatchGetReq) returns (SCCacheApiBatchGetRsp) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "批量拉取数据（并订阅）"
      frequency_limit: { frequency_limit_ms: 10000 frequency_limit_count: 100 }
    };
  };

  // 反订阅
  rpc cache_api_unwatch(CSCacheApiUnwatchReq) returns (SCCacheApiUnwatchRsp) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "反订阅"
      frequency_limit: { frequency_limit_ms: 5000 frequency_limit_count: 30 }
    };
  };

  // 指定缓存数据失效通知
  rpc cache_api_expired(google.protobuf.Empty) returns (stream SCCacheApiExpiredSync) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "指定缓存数据失效通知"
      no_cache: true
    };
  };

  // Meta信息更新(缓存数据的简化版本)通知
  rpc cache_api_update_meta(google.protobuf.Empty) returns (stream SCCacheApiUpdateMetaSync) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "Meta信息更新(缓存数据的简化版本)通知"
      no_cache: true
    };
  };

  // 全部缓存数据失效通知
  rpc cache_api_all_expired(google.protobuf.Empty) returns (stream SCCacheApiAllExpiredSync) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "全部缓存数据失效通知"
      no_cache: true
    };
  };

  // 主动通知服务器更新meta
  rpc cache_api_notify_meta(CSCacheApiNotifyMetaReq) returns (SCCacheApiNotifyMetaRsp) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "主动通知服务器更新meta"
      frequency_limit: { frequency_limit_ms: 5000 frequency_limit_count: 30 }
    };
  };

  // ================ 聊天RPC ================
  rpc chat_get_all_channel(atframework.chat.CSChatGetAllChannelReq) returns (atframework.chat.SCChatGetAllChannelRsp) {
    // 此接口仅返回频道的meta信息，实际开始接收数据要在下面对每个频道发送 CSChatGetChannelSnapshotReq 拉取初始快照后
    option (atframework.rpc_options) = {
      module_name: "chat"
      api_name: "获取所有聊天频道"
    };
  };

  rpc chat_get_channel_snapshot(atframework.chat.CSChatGetChannelSnapshotReq) returns (atframework.chat.SCChatGetChannelSnapshotRsp) {
    // 拉取初始快照后才会开始收到推送消息
    option (atframework.rpc_options) = {
      module_name: "chat"
      api_name: "获取聊天频道快照"
    };
  };

  rpc chat_channel_heartbeat(atframework.chat.CSChatChannelHeartbeatReq) returns (atframework.chat.SCChatChannelHeartbeatRsp) {
    option (atframework.rpc_options) = {
      module_name: "chat"
      api_name: "聊天频道心跳"
    };
  };

  rpc chat_channel_sync(google.protobuf.Empty) returns (stream atframework.chat.SCChatChannelSync) {
    option (atframework.rpc_options) = {
      module_name: "chat"
      api_name: "聊天频道推送同步"
    };
  };

  rpc chat_send_message(atframework.chat.CSChatSendMessageReq) returns (atframework.chat.SCChatSendMessageRsp) {
    option (atframework.rpc_options) = {
      module_name: "chat"
      api_name: "发送聊天消息"
    };
  };
}
