syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

import "protocol/common/com.struct.dtmq.common.proto";
import "protocol/pbdesc/com.struct.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

package atframework.chat;

enum EnChatChannelType {
  EN_CHAT_CHANNEL_TYPE_INVALID = 0;
  EN_CHAT_CHANNEL_TYPE_PUBLIC = 1;        // 公共频道 Channel
  EN_CHAT_CHANNEL_TYPE_PRIVATE = 2;       // 私聊用户 Channel
  EN_CHAT_CHANNEL_TYPE_TEAM = 3;          // 组队频道 Channel
  EN_CHAT_CHANNEL_TYPE_SYS_NOTIFY = 4;    // 系统通知 Channel
  EN_CHAT_CHANNEL_TYPE_TOP_BOARD = 5;     // 跑马灯 Channel
  EN_CHAT_CHANNEL_TYPE_PRIVATE_ROOM = 6;  // 私人房间 Channel
}
