syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/extension/atframework.proto";
import "protocol/pbdesc/com.struct.orbit.proto";

package atframework.shared;

service OrbitServerRpcService {
  option (atframework.service_options) = {
    module_name: "orbit_server_rpc"
  };

  rpc echo(OrbitServerEchoReq) returns (OrbitServerEchoRsp);
  rpc user_finish(OrbitServerUserFinishReq) returns (OrbitServerUserFinishRsp);
}

message OrbitServerEchoReq {
  string text = 1;
}

message OrbitServerEchoRsp {
  string text = 1;
}

service OrbitClientRpcService {
  option (atframework.service_options) = {
    module_name: "orbit_client_rpc"
  };

  rpc echo(OrbitClientEchoReq) returns (OrbitClientEchoRsp);
  rpc user_init(OrbitClientUserInitReq) returns (OrbitClientUserInitRsp);
}

message OrbitClientEchoReq {
  string text = 1;
}

message OrbitClientEchoRsp {
  string text = 1;
}

message OrbitClientUserInitReq {
  repeated DOrbitUserInitData user_data = 1;
  bool init_finish = 2;
}

message OrbitClientUserInitRsp {
  int32 ret_code = 1;
  repeated DOrbitUserInitResult data = 2;
}

message OrbitServerUserFinishReq {
  repeated DOrbitUserFinishResult results = 1;
}

message OrbitServerUserFinishRsp {}