syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";

import "protocol/pbdesc/com.struct.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

package atframework.team;

// 注意和DtMq.xlsx 表对应，多个模块之间类型不要冲突
enum EnTeamChannelType {
  EN_TEAM_CHANNEL_TYPE_INVALID = 0;
  EN_TEAM_CHANNEL_TYPE_TEAM_ROOM = 11;  // 组队房间
}

enum DTeamExitReason {
  EN_TEAM_EXIT_REASON_DEFAULT = 0;
  EN_TEAM_EXIT_REASON_LOGOUT = 1;
  EN_TEAM_EXIT_REASON_EXPIRED = 2;
  EN_TEAM_EXIT_REASON_DESTROY_TEAM = 3;
  EN_TEAM_EXIT_REASON_REMOVE_MEMBER = 4;
  EN_TEAM_EXIT_REASON_CANCEL = 5;
  EN_TEAM_EXIT_REASON_UNSUBSCRIBE_TEAM_CHANNEL = 6;
  EN_TEAM_EXIT_REASON_OFFLINE_EXPIRED = 7;
  EN_TEAM_EXIT_REASON_EXIT_TEAM = 8;
  EN_TEAM_EXIT_REASON_UPDATE_CUSTOM_LOCK_ERROR = 11;
  EN_TEAM_EXIT_REASON_MODULE_BAN = 12;
  EN_TEAM_EXIT_REASON_IN_ANOTHER_TEAM = 13;
}

enum EnTeamAdmissionCancelReason {
  EN_TEAM_INVITATION_CANCEL_REASON_UNKNOWN = 0;
  EN_TEAM_INVITATION_CANCEL_REASON_TEAM_ID_NOT_MATCHED = 1;
  EN_TEAM_INVITATION_CANCEL_REASON_IS_MATCHING = 2;
  EN_TEAM_INVITATION_CANCEL_REASON_IS_IN_BATTLE = 3;
  EN_TEAM_INVITATION_CANCEL_REASON_TEAM_FULL = 4;
  EN_TEAM_INVITATION_CANCEL_REASON_IS_IN_TEAM = 5;
  EN_TEAM_INVITATION_CANCEL_REASON_TIMEOUT = 6;
  EN_TEAM_INVITATION_CANCEL_REASON_IS_PRE_SEARCH = 7;
  EN_TEAM_INVITATION_CANCEL_REASON_SEASON_ROLE_NOT_FOUND = 8;
  EN_TEAM_INVITATION_CANCEL_REASON_IS_IN_PRIVATE_ROOM = 9;
  EN_TEAM_INVITATION_CANCEL_REASON_MODULE_UNLOCK = 10;
  EN_TEAM_INVITATION_CANCEL_REASON_SEASON_NOT_MATCH = 11;
}

enum EnTeamAdmissionRejectReason {
  EN_TEAM_INVITATION_REJECT_REASON_UNKNOWN = 0;
  EN_TEAM_INVITATION_REJECT_REASON_INVITEE_REJECT = 1;
  EN_TEAM_INVITATION_REJECT_REASON_IS_IN_TEAM = 2;
  EN_TEAM_INVITATION_REJECT_REASON_MODULE_BAN = 3;
  EN_TEAM_INVITATION_REJECT_REASON_IS_IN_MATCHING = 4;
  EN_TEAM_INVITATION_REJECT_REASON_IS_IN_BATTLE = 5;
  EN_TEAM_INVITATION_REJECT_REASON_IS_PRE_SEARCH = 6;
  EN_TEAM_INVITATION_REJECT_REASON_SEASON_NOT_MATCH = 7;
}

enum EnTeamSourceType {
  EN_TEAM_SOURCE_TYPE_NONE = 0;
  EN_TEAM_SOURCE_TYPE_SNS_PLATFORM = 1;
  EN_TEAM_SOURCE_TYPE_FRIEND = 2;
  EN_TEAM_SOURCE_TYPE_MATCH = 3;
  EN_TEAM_SOURCE_TYPE_BATTLE = 4;
}

enum EnTeamPermissionType {
  EN_TEAM_PERMISSION_TYPE_PUBLIC = 0;
  EN_TEAM_PERMISSION_TYPE_MEMBER = 1;
}

message DTeamAnyData {
  EnTeamPermissionType permission = 1;
  google.protobuf.Any data = 2;
}

message DTeamKey {
  int64 team_id = 1;
}

enum EnTeamPermissionRole {
  EN_TEAM_MEMBER_ROLE_GUEST = 0;
  EN_TEAM_MEMBER_ROLE_NORMAL = 1;
  EN_TEAM_MEMBER_ROLE_OWNER = 2;
  EN_TEAM_MEMBER_ROLE_ADMIN = 3;
}

message DTeamMember {
  atframework.shared.DUserIDKey user_key = 1;
  // 入队时间
  google.protobuf.Timestamp joined_timepoint = 2;

  EnTeamPermissionRole role = 3;

  // 入队方式和额外数据
  EnTeamSourceType team_source_type = 4;
  google.protobuf.Any team_source_data = 5;

  // 退出原因
  DTeamExitReason remove_member_reason = 6;

  string client_version = 7;
  uint64 user_router_server_id = 8;

  // 最后收到的组队通道的消息sequence和hash code
  int64 acknowledge_action_sequence = 11;
  uint64 acknowledge_action_hash_code = 12;

  // 共享的成员数据，通常是阵容信息、状态信息等。
  // 数据按key-value形式下发，注意各个模块使用时key要区分开
  map<int32, DTeamAnyData> shared_member_data = 13;
}

message DTeamAdmissionResult {
  atframework.shared.DUserIDKey inviter = 1;
  atframework.shared.DUserIDKey invitee = 2;
  DTeamKey team_key = 3;

  EnTeamAdmissionCancelReason cancel_reason = 21;
  EnTeamAdmissionRejectReason reject_reason = 22;
}

message DTeamInvitation {
  atframework.shared.DUserIDKey inviter = 1;
  atframework.shared.DUserIDKey invitee = 2;
  DTeamKey team_key = 3;

  EnTeamSourceType team_source_type = 4;
  google.protobuf.Any team_source_data = 5;

  // 开始事件
  google.protobuf.Timestamp start_timepoint = 8;
  // 失效时间
  google.protobuf.Timestamp expired_timepoint = 9;

  // 共享的发邀请或盛情加入请求的数据，通常是状态信息的子集。
  // 数据按key-value形式下发，注意各个模块使用时key要区分开
  map<int32, DTeamAnyData> member_admission_data = 14;
}

message DTeamJoinRequest {
  DTeamKey team_key = 1;
  atframework.shared.DUserIDKey user_key = 2;

  EnTeamSourceType team_source_type = 3;
  google.protobuf.Any team_source_data = 4;

  string client_version = 6;
  uint64 user_router_server_id = 7;

  // 过期时间
  google.protobuf.Timestamp expired_timepoint = 8;

  // 共享的发邀请或盛情加入请求的数据，通常是状态信息的子集。
  // 数据按key-value形式下发，注意各个模块使用时key要区分开
  map<int32, DTeamAnyData> member_admission_data = 14;
}

message DTeamConfigure {}

message DTeamStorage {
  DTeamKey team_key = 1;
  // 当前队长
  atframework.shared.DUserIDKey captain_user_key = 2;

  DTeamConfigure configure = 3;

  // 当前成员
  repeated DTeamMember member = 6;

  // 当前待处理的申请列表
  repeated DTeamJoinRequest pending_apply = 7;

  // 当前待处理的邀请列表
  repeated DTeamInvitation pending_invitation = 8;

  // 最后收到的组队通道的消息sequence和hash code
  int64 acknowledge_action_sequence = 11;
  uint64 acknowledge_action_hash_code = 12;
  // 已保存的数据sequence，这之前的数据log可以压缩
  int64 saved_action_sequence = 13;

  // 共享的队伍数据，通常是当前关卡、模式、匹配信息等。
  // 数据按key-value形式下发，注意各个模块使用时key要区分开
  map<int32, DTeamAnyData> shared_team_data = 14;
}

message DTeamAction {
  oneof action {
    DTeamKey destroy_team = 1;  // 有这个消息或者订阅失败则视为小队已解散
    // DTeamHeartBeatInfo heartbeat = 2;  // 定期ping包，防止聊天频道过期销毁
    DTeamMember add_member = 3;
    DTeamMember remove_member = 4;
    DTeamMember member_confirm = 5;  // 队员准备
    // DTeamMember cancel_wait = 6;                    // 取消等待，直接进入队伍房间
    DTeamMember election_captain = 7;  // 重新选出的队长
  }
}

message DTeamMemberAction {
  oneof action {
    DTeamInvitation invited = 1;
    DTeamInvitation reject_invitation = 2;
    DTeamInvitation cancel_invitation = 3;

    DTeamJoinRequest apply_join_request = 8;
    DTeamJoinRequest reject_join_request = 5;
    DTeamJoinRequest cancel_join_request = 6;

    DTeamInvitation join_in_team = 4;
    DTeamMember remove_member = 7;
  }
}
