syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/common/com.struct.dtmq.common.proto";
import "protocol/pbdesc/com.struct.chat.proto";
import "protocol/pbdesc/com.struct.dtmq.proto";

package atframework.chat;

message CSChatGetAllChannelReq {}

message SCChatGetAllChannelRsp {
  repeated DChatChannelMeta channel_metadata = 1;
}

message CSChatGetChannelSnapshotReq {
  string channel_id = 1;
}

message SCChatGetChannelSnapshotRsp {
  DChatChannelData channel_snapshot = 1;
}

message CSChatChannelHeartbeatReq {
  repeated atframework.dtmq.DChannelSyncPoint heartbeat_data = 1;
}

message SCChatChannelHeartbeatRsp {}

message SCChatChannelSync {
  repeated DChatChannelData chat_channel = 1;
}

message CSChatSendMessageReq {
  atframework.dtmq.DChannelIdKey channel_key = 1;
  atframework.dtmq.DChannelMessageDetail detail = 2;
}

message SCChatSendMessageRsp {
  atframework.dtmq.DChannelMessage msg = 1;
}
