syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

package atframework.shared;

import "protocol/pbdesc/com.struct.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

message DUserDataBasicCache {
  // 业务数据
}

message DUserBasicDataMetaLogin {
  int64 business_register_time = 1;    // 业务层注册时间
  int64 business_login_time = 2;       // 业务层登入时间
  int64 business_logout_time = 3;      // 业务层登出时间
  int64 business_unregister_time = 4;  // 业务层注销时间
}

message DUserBasicDataMetaProfile {
  string open_id = 1;
}

message DUserBasicDataMeta {
  DUserIDKey user_key = 1;
  DUserBasicDataMetaLogin login_data = 2;
  DUserBasicDataMetaProfile profile = 3;
  uint64 user_data_version = 11;
}

// 用户基础信息（允许客户端批量拉）
message DUserBasicData {
  DUserBasicDataMeta meta_data = 1;
  DUserSharedOptions shared_options = 11;  // 公开的用户自定义选项
  DUserDataBasicCache basic_cache = 12;    // 用户基础缓存数据
}

message DCacheApiObjectData {
  oneof object_data {
    DUserBasicData user_cache = 11;
  }
}

message DCacheApiMetaData {
  oneof meta_data {
    DUserBasicDataMeta user_meta = 11;
  }
}
