syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/pbdesc/com.struct.friend_api.proto";
import "protocol/pbdesc/com.struct.proto";

package atframework.friend_api;

// 获取好友数据
message CSFriendGetAllReq {}

message SCFriendGetAllRsp {
  DFriendStatistics stats = 1;                              // 统计数据，限频数据
  repeated DFriendGiftHistory daily_send_list = 2;     // 今日已赠送列表
  repeated DFriendGiftHistory daily_receive_list = 3;  // 今日已收取列表

  repeated DFriendInfo friend_list = 11;
  repeated DFriendInvitationInfo inviter_list = 12;
  repeated DFriendInvitationInfo invitee_list = 13;
  repeated DFriendGift gift_list = 14;

  repeated DFriendSNSInfo sns_friend_list = 21;  // 社交平台好友信息
  // repeated SNSShareCfgData sns_share_cfg = 22;   // 社交分享功能配置
  // UserSNSData sns_data = 23;                     // 社交平台分享和上报数据
}

// 发送好友申请
message CSFriendInvitationReq {
  atframework.shared.DUserIDKey user_key = 1;

  // 也可以不填上面的参数使用account_id
  uint64 account_id = 3;
}

message SCFriendInvitationRsp {}

// 接受好友申请
message CSFriendAcceptInvitationReq {
  atframework.shared.DUserIDKey user_key = 1;
}

message SCFriendAcceptInvitationRsp {}

// 拒绝好友申请
message CSFriendRejectInvitationReq {
  atframework.shared.DUserIDKey user_key = 1;
}

message SCFriendRejectInvitationRsp {}

// 删除好友
message CSFriendRemoveReq {
  atframework.shared.DUserIDKey user_key = 1;
}

message SCFriendRemoveRsp {}

message CSFriendSendGiftReq {
  atframework.shared.DUserIDKey user_key = 1;
  int32 gift_type_id = 3;
}

message SCFriendSendGiftRsp {}

message CSFriendReceiveGiftReq {
  repeated int64 gift_ids = 1;
}

message SCFriendReceiveGiftRsp {
  repeated DFriendGift receive_gifts = 1;
}

message CSFriendGetSuggestReq {
  // EnForceType force_type = 1;
}

message SCFriendGetSuggestRsp {
  repeated DFriendSuggestInfo suggest_users = 1;
}

// 一键同意所有好友
message CSFriendAcceptAllInvitationReq {}

message SCFriendAcceptAllInvitationRsp {}

// 一键拒绝所有好友
message CSFriendRejectAllInvitationReq {}

message SCFriendRejectAllInvitationRsp {}
