syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

import "protocol/pbdesc/com.struct.proto";
import "protocol/pbdesc/com.struct.team.proto";

package atframework.shared;

// 本文件用于存放和业务内容有关的组队共享数据定义，而 com.struct.team.proto 是和业务内容无关的定义

enum EnTeamType {
  EN_TEAM_TYPE_INVALID = 0;  // 无效类型
  EN_TEAM_TYPE_NORMAL = 1;   // 普通组队
}

// ======================== 队伍数据内容定义 ========================
message DTeamSharedDataTypeBattle {
  oneof data_type {
    bool matching = 1;  // 匹配中
  }
}

// ------------------------ 队伍数据模块定义 ------------------------
// Key的算法:
// - 高32位: module_type oneof 中被设置字段的 field number
// - 低32位: 二级 data_type oneof 中被设置字段的 field number
// 生成与解析必须与 user_team_algorithm::make_team_shared_data_key 保持一致
message DTeamSharedDataModule {
  oneof module_type {
    DTeamSharedDataTypeBattle battle = 1;
  }
}

// ======================== 队伍成员数据内容定义 ========================
message DTeamMemberSharedDataTypeBattle {
  oneof data_type {
    bool ready = 1;  // 准备就绪
  }
}

// ------------------------ 队伍成员数据模块定义 ------------------------
// Key的算法:
// - 高32位: module_type oneof 中被设置字段的 field number
// - 低32位: 二级 data_type oneof 中被设置字段的 field number
// 生成与解析必须与 user_team_algorithm::make_team_member_shared_data_key 保持一致
message DTeamMemberSharedDataModule {
  oneof module_type {
    DTeamMemberSharedDataTypeBattle battle = 1;
  }
}


// ======================== 队伍脏数据下发数据 ========================
message DUserTeamSnapshot {
  atframework.team.DTeamStorage snapshot = 1;

  // snapshot里的队伍共享数据（解包后）
  repeated DTeamSharedDataModule shared_team_data = 2;

  message UnpackedMemberSharedData {
    atframework.shared.DUserIDKey user_key = 1;
    // 解包后的队伍成员共享数据
    repeated DTeamMemberSharedDataModule shared_member_data = 2;
  }

  repeated UnpackedMemberSharedData unpacked_member_data = 3;
}

message DUserTeamDirty {
  message OneAction {
    atframework.team.DTeamAction action = 1;

    // actions里的队伍成员共享数据（如果有，解包后）
    repeated DTeamMemberSharedDataModule shared_member_data = 2;
  }

  message Increase {
    atframework.team.DTeamKey team_key = 1;
    repeated OneAction actions = 2;
  }

  oneof dirty_type {
    DUserTeamSnapshot snapshot = 1;
    Increase increase = 2;
  }
}
