syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

package hello;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/pbdesc";

enum EnGenderType {
  EN_GENDER_TYPE_UNKNOWN = 0;
  EN_GENDER_TYPE_MALE = 1;
  EN_GENDER_TYPE_FEMALE = 2;
}

// 登录用户终端信息
message DClientDeviceInfo {
  uint32 system_id = 1;                // EnSystemID
  string client_version = 2;           // 客户端版本号
  string system_software = 3;          // 移动终端操作系统版本
  string system_hardware = 4;          // 移动终端机型
  string telecom_operator = 5;         // 运营商
  string network = 6;                  // WIFI/3G/2G
  uint32 reg_channel = 7;              // 注册渠道
  uint32 screen_width = 8;             // 显示屏宽度
  uint32 screen_hight = 9;             // ScreenHight
  float density = 10;                  // 像素密度
  string cpu_info = 11;                // 类型#核数#频率
  uint32 memory = 12;                  // 内存信息单位M
  string glrender = 13;                // opengl render信息
  string glversion = 14;               // opengl版本信息
  string channel = 15;                 // 登录渠道
  string device_id = 16;               // 设备ID
  uint32 version = 17;                 // 客户端数字版本号
  int32 well_known_simulator_id = 18;  // 模拟器ID
}

message DAppleGameCenter {
  // 一个都不能少
  string player_id = 1;            //
  string public_key_url = 2;       //
  string signature = 3;            //
  string encoded_signed_data = 4;  // 由player_id and salt and bundle_id and timestamp生成
  string salt = 5;                 //
  string bundle_id = 6;            //
  int64 timestamp = 7;             //
}

// 平台信息
message DAccountData {
  uint32 account_type = 1;  // 平台类型 EnAccountTypeID
  string access = 2;        // 授权码（内置账户的话就是密码的hash值，OAuth的话就是access token）
  uint32 channel_id = 3;    // 渠道ID（某些品太需要区分认证体系以外的渠道号） @see EnPlatformChannelID
}

message DUpdateData {
  int32 result = 1;
  int32 version = 2;
  string url = 3;
}

// 更新信息
message DClientUpdateCfg {
  int32 result = 1;    // @ENUpdateType
  string cdn_url = 2;  // 网址前缀

  DUpdateData res_data = 3;  // 资源包
  DUpdateData app_data = 4;  // app包
}

// 用户profile
message DUserProfile {
  string open_id = 1;
  uint64 user_id = 2;
  string nick_name = 3;
  string logo_url = 4;
  EnGenderType gender = 5;

  string custom_nick_name = 11;  // 玩家自定义昵称
}

// 用户profile
message DUserStatistics {
  int64 register_time = 1;    // 注册时间
  int64 last_login_time = 2;  // 上次登录时间
}

// 用户数据
message DUserInformation {
  DUserProfile profile = 1;
  int32 user_level = 2;  // 玩家（主城）等级
  DUserStatistics user_statistics = 4;
}

// 用户自定义选项
message DUserOptions {}

message DUserIDKey {
  uint64 user_id = 1;
  uint32 zone_id = 2;
}

message DUserAccountIDRefer {
  uint64 user_id = 1;
  uint32 zone_id = 2;
  // uint64 account_id = 3;
}

// 用户公开选项
message DUserSharedOptions {}

// 用户私有选项
message DUserPrivateOptions {
  // 客户端自定义选项数据，长度受 Const.xlsx 的 user_options_max_size 选项限制
  bytes client_options = 1;
}

// 用户基础信息（允许客户端批量拉）
message DUserBasicData {
  DUserIDKey user_key = 1;
  uint32 account_type = 2;           // @see EnAccountType
  uint32 account_login_channel = 3;  // @see EnPlatformChannelID
  // uint64 account_id = 4;
  DLoginBasicDataCache login_data_cache = 5;
  string client_version = 6;

  DUserProfile profile = 31;             // 用户账号属性
  uint32 package_register_channel = 35;  // 包注册渠道号
  uint32 package_login_channel = 36;     // 包登录渠道号
  int32 version_type = 37;               // 上一次的登入版本类型 @EnVersionType

  int32 user_level = 51;          // 玩家等级
  uint64 user_data_version = 53;  // data version

  DUserSharedOptions shared_options = 101;  // 公开的用户自定义选项
}

message DLoginBasicDataCache {
  string access_token_code = 11;                        // 认证码
  google.protobuf.Timestamp access_token_expired = 12;  // 认证码过期时间

  // 业务层登入注册信息
  int64 business_register_time = 31;    // 业务层注册时间
  int64 business_login_time = 32;       // 业务层登入时间
  int64 business_logout_time = 33;      // 业务层登出时间
  int64 business_unregister_time = 34;  // 业务层注销时间
}

/////////////////////////////////////////////////////////////////////////
// 好友数据
/////////////////////////////////////////////////////////////////////////

// 用户好友礼物数据

// 用户好友赠送记录

// 用户好友礼物控制选项

// 用户新手选项数据

// 用户处罚禁止选项

// 用户选项

// 用户排行相关数据

// 用户好友数据

// 好友关卡信息

// 好友缓存数据

// 用户好友数据

// ====================== 角色人物相关数据 ======================
