{{- template "libapp.configmap" (list . "orbit-server.configmap") -}}
{{- define "orbit-server.configmap" -}}
data:
  {{ include "orbit-server.name" . }}.yaml: {{ tpl (.Files.Get "cfg/orbit-server.yaml.tpl") . | quote }}
{{- end -}}
