syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

package orbit;

import "protocol/common/orbit.common.proto";

/////////////// Controller -> Server ///////////////
service ControllerToServerService {
  rpc forward_to_server(CTSForwardToServerReq) returns (STCForwardToServerRsp) {
    option (atframework.rpc_options) = {
      api_name: "转发Client消息"
    };
  };

  rpc client_start_notify(CTSClientStartReq) returns (STCClientStartRsp) {
    option (atframework.rpc_options) = {
      api_name: "Client启动通知"
    };
  };

  rpc client_end_notify(CTSClientEndReq) returns (STCClientEndRsp) {
    option (atframework.rpc_options) = {
      api_name: "Client退出通知"
    };
  };

  rpc client_agent_heartbeat(stream CTSClientAgentHeartbeatNotify) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "Client心跳通知"
    };
  };
}

message CTSForwardToServerReq {
  DClientMessage client_message = 1;
}
message STCForwardToServerRsp {
  int32 error_code = 1;
}

message CTSClientStartReq {
  DClientIdentity client_identity = 1;

  string client_addr = 2;
  bytes data = 3;
}
message STCClientStartRsp {
  int32 error_code = 1;
}

message CTSClientEndReq {
  DClientIdentity client_identity = 1;

  EnClientExitReason exit_reason = 11;
  bytes exit_data = 12;
  int32 exit_code = 13;
}
message STCClientEndRsp {
  int32 error_code = 1;
}

message CTSClientAgentHeartbeatNotify {
  DAgentIdentity agent_identity = 1;
  repeated DClientId client_ids = 2;
}

/////////////// Server -> Controller ///////////////
service ServerToControllerService {
  rpc launch_client(STCLaunchClientReq) returns (CTSLaunchClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "启动Client 返回不等于可用"
    };
  };
  rpc send_to_client(STCSendToClientReq) returns (CTSSendToClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "发送消息至Client"
      allow_no_wait: true
    };
  };
  rpc server_heartbeat(stream STCServerHeartbeatNotify) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "Server心跳"
    };
  };
}

message STCLaunchClientReq {
  DServerIdentity server_identity = 1;

  DAgentClientStartArgs args = 2;
  string match_tag = 3;
}
message CTSLaunchClientRsp {
  int32 error_code = 1;
}

message STCSendToClientReq {
  DServerIdentity server_identity = 1;

  DClientIdentity client_identity = 2;
  bytes payload = 3;
}
message CTSSendToClientRsp {
  int32 error_code = 1;
}

message STCServerHeartbeatNotify {
  DServerIdentity server_identity = 1;
  repeated DAgentIdentity agent_identity = 2;
}