syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

import "protocol/extension/xrescode_extensions_v3.proto";
import "protocol/extension/v3/xresloader.proto";

import "protocol/common/com.struct.team.common.proto";

option go_package = "github.com/atframework/atsf4g-co/component/public/protocol/config";

package atframework.shared.config;

// 组队类型配置
message ExcelTeamType {
  option (xrescode.loader) = {
    file_path: "team_type.bytes"
    indexes: { fields: "team_type" index_type: EN_INDEX_KV }

    tags: "client"
    tags: "server"
  };

  uint32 team_type = 1
      [(org.xresloader.field_unique_tag) = "team_type", (org.xresloader.validator) = "atframework.shared.EnTeamType"];

  atframework.team.DTeamConfigure configure = 2;
}
