syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

package atframework.orbit;

import "protocol/common/orbit.common.proto";

service AgentToControllerService {
  rpc notify_client_started(ATCNotifyClientStartedReq) returns (CTANotifyClientStartedRsp) {
    option (atframework.rpc_options) = {
      api_name: "通知Client已启动"
    };
  };
  rpc notify_client_exit(ATCNotifyClientExitReq) returns (CTANotifyClientExitRsp) {
    option (atframework.rpc_options) = {
      api_name: "通知Client已退出"
    };
  };
  rpc forward_to_server(ATCForwardToServerReq) returns (CTAForwardToServerRsp) {
    option (atframework.rpc_options) = {
      api_name: "转发至Server"
    };
  };
  rpc agent_heartbeat(stream ATCAgentHeartbeatReq) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "Agent心跳"
    };
  };
}

message ATCNotifyClientStartedReq {
  DServerIdentity server_identity = 1;

  DClientIdentity client_identity = 2;

  string client_addr = 3;
  bytes custom_data = 4;
}
message CTANotifyClientStartedRsp {
  int32 error_code = 1;
}

message ATCNotifyClientExitReq {
  DServerIdentity server_identity = 1;

  DClientIdentity client_identity = 2;

  EnClientExitReason exit_reason = 11;
  bytes custom_data = 12;
  int32 exit_code = 13;
}
message CTANotifyClientExitRsp {
  int32 error_code = 1;
}

message ATCForwardToServerReq {
  DServerIdentity server_identity = 1;

  DClientMessage client_message = 2;
}
message CTAForwardToServerRsp {
  int32 error_code = 1;
}

message ATCAgentHeartbeatReq {
  DServerIdentity server_identity = 1;

  DAgentIdentity agent_identity = 2;
  repeated DClientId client_ids = 3;
}