syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "protocol/extension/atframework.proto";

import "protocol/pbdesc/com.struct.orbit.proto";

package atframework.shared;

message SSOrbitCreateRoomReq {
  DOrbitRoomKey room_key = 1;
  DOrbitRoomInitData room_data = 2;
}

message SSOrbitCreateRoomRsp {
  int32 result_code = 1;
}

message SSOrbitUserInitReq {
  DOrbitRoomKey room_key = 1;
  repeated DOrbitUserInitData user_list = 2;
  bool is_last_one = 3;
}

message SSOrbitUserInitRsp {
  int32 result_code = 1;
}

service OrbitsvrService {
  option (atframework.service_options) = {
    module_name: "orbit"
  };

  rpc create_room(SSOrbitCreateRoomReq) returns (SSOrbitCreateRoomRsp) {
    option (atframework.rpc_options) = {
      api_name: "创建战斗房间"
    };
  };

  rpc init_user(SSOrbitUserInitReq) returns (SSOrbitUserInitRsp) {
    option (atframework.rpc_options) = {
      api_name: "初始化用户"
    };
  };
}
