syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

import "google/protobuf/duration.proto";

import "atframe/atapp_conf.proto";

option go_package = "github.com/atframework/atsf4g-co/lobbysvr/protocol/protocol/config";

package atframework.shared.config;

message lobbysvr_chat_cfg {
  int64 push_message_per_second = 1
      [(atframework.atapp.protocol.CONFIGURE) = { default_value: "3000" min_value: "30" }];
  int64 push_message_buffer_max_count = 2
      [(atframework.atapp.protocol.CONFIGURE) = { default_value: "200000" min_value: "100" }];
}

message lobbysvr_team_cfg {
  google.protobuf.Duration exit_retry_interval = 1
      [(atframework.atapp.protocol.CONFIGURE) = { default_value: "10s" min_value: "1s" }];
}

message lobbysvr_cfg {
  google.protobuf.Duration rank_auto_update_interval = 101
      [(atframework.atapp.protocol.CONFIGURE) = { default_value: "3600s" min_value: "30s" }];  // 排行榜强制刷新间隔
  lobbysvr_chat_cfg chat = 201;
  lobbysvr_team_cfg team = 202;
}
