# Matching robot demo.
# Format: case error_break openid_prefix id_start id_end target_qps user_batch_count run_time [args...]
login true robot_matching_ 1001 1006 0 1 1
matching_start true robot_matching_ 1001 1006 0 1 1 1 1 cn
matching_wait true robot_matching_ 1001 1006 0 1 1 30 3
matching_confirm true robot_matching_ 1001 1006 0 1 1 true
logout true robot_matching_ 1001 1006 0 1 1
