# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: orbit-controllerd

type_id: 27
type_name: "orbit-controller"

image:
  repository: harbor.m-oa.com:6023/project-x/orbit-controller
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/orbit-controller/cfg
  logMountPath: /data/atframework/publish/orbit-controller/log

vector:
  enabled: false
  log_path: /data/atframework/publish/orbit-controller/log

orbit_controller:
  region: default
  agent_discovery_path: /atapp/services/atsf4g-co-orbit