syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

import "protocol/pbdesc/svr.struct.proto";
import "protocol/pbdesc/svr.struct.cache.proto";
import "protocol/pbdesc/com.struct.orbit.proto";
import "protocol/pbdesc/com.struct.proto";

option go_package = "github.com/atframework/atsf4g-co/lobbysvr/protocol/protocol/pbdesc";

package atframework.shard;

/////////////////////////////////////////////////////
////  此处开始是登入相关协议
/////////////////////////////////////////////////////

message SSPlayerKickOffReq {
  uint32 reason = 1;          // 原因
  string reason_message = 2;  // 原因文本
}

message SSPlayerKickOffRsp {}

message SSPlayerAsyncJobsSync {}
/////////////////////////////////////////////////////
////  登入相关协议到此结束
/////////////////////////////////////////////////////

/////////////////////////////////////////////////////
////  此处开始是缓存服的协议
/////////////////////////////////////////////////////

// ====== 过期通知 ======
message SSObjectCacheExpiredSync {
  repeated object_cache_watcher watchers = 11;
  object_cache_key expired_key = 21;  // 过期的缓存对象ID
}

// ====== Meta信息刷新通知 ======
message SSObjectCacheMetaSync {
  repeated object_cache_watcher watchers = 11;
  object_cache_meta update_meta = 21;  // 要刷新的cache meta
}

// ====== 拉取用户缓存信息 ======
message SSObjectCacheGetUserCacheDataReq {
  object_cache_key key = 1;
}

// ====== 拉取用户缓存信息 ======
message SSObjectCacheGetUserCacheDataRsp {
  int32 result = 1;
  object_cache_meta cache_meta = 2;  // 要刷新的cache meta
}

/////////////////////////////////////////////////////
////  缓存服的协议到此结束
/////////////////////////////////////////////////////

message SSOrbitRoomEventSync {
  DOrbitRoomKey room_key = 1;                  // 房间key
  repeated DUserIDKey user_keys = 2;           // 要同步的玩家列表
  repeated DOrbitRoomEventLog event_logs = 3;  // 事件列表
  DOrbitRoomSnapshotData room_snapshot = 4;    // 房间快照
}

// 提供 lobbysvr 内部服务之间的 RPC 接口定义。
service LobbysvrService {
  option (atframework.service_options) = {
    module_name: "lobby"
  };

  // 通知目标玩家下线。
  rpc player_kickoff(SSPlayerKickOffReq) returns (SSPlayerKickOffRsp) {
    option (atframework.rpc_options) = {
      module_name: "player"
      api_name: "通知提用户下线"
      user_rpc: true
    };
  };

  // 通知其他服务实例同步并执行异步任务。
  rpc player_async_jobs_sync(stream SSPlayerAsyncJobsSync) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      module_name: "player"
      api_name: "通知更新和执行异步任务"
      descriptions: "notify another server instance to sync async jobs"
      user_rpc: true
    };
  };

  // 通知其他服务实例将指定缓存对象标记为过期。
  rpc object_cache_expired_sync(stream SSObjectCacheExpiredSync) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "缓存过期事件通知"
      descriptions: "notify another server instance to set cache expired"
    };
  };

  // 通知其他服务实例刷新指定缓存对象的 Meta 信息。
  rpc object_cache_meta_sync(stream SSObjectCacheMetaSync) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "缓存刷新Meta事件通知"
      descriptions: "notify another server instance to update cache meta"
    };
  };

  // 拉取用户缓存信息
  rpc object_cache_get_user_cache_data(SSObjectCacheGetUserCacheDataReq) returns (SSObjectCacheGetUserCacheDataRsp) {
    option (atframework.rpc_options) = {
      module_name: "cache"
      api_name: "拉取用户缓存信息"
      user_rpc: true
    };
  };

  rpc orbit_room_event_sync(stream SSOrbitRoomEventSync) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      module_name: "orbit"
      api_name: "房间事件通知"
      descriptions: "notify another server instance to sync orbit room events"
    };
  };
}
