# Copyright 2026 atframework
# Licensed under the Apache License, Version 2.0 (the "License");

include_guard(GLOBAL)

# cmake-format: off
# project_add_normal_unit_test(
#   TARGET <target>                         # required, executable target name
#   COMPONENT <component-name>              # required, used for stable labels
#   CATEGORY <component|sdk|service|tool>   # optional, defaults to "component"
#   SOURCES <a.cpp> [<b.cpp> ...]           # required
#   LINK_LIBRARIES <targets...>              # optional link dependencies
#   DEPENDENCIES <targets...>                # optional build-only dependencies
#   INCLUDE_DIRECTORIES <directories...>     # optional private include directories
#   COMPILE_DEFINITIONS <definitions...>     # optional private compile definitions
#   COMPILE_OPTIONS <options...>             # optional private compile options
#   PCH_REUSE_FROM_TARGETS <targets...>       # optional extra PCH reuse candidates
#   LABELS <extra ctest labels...>
#   TIMEOUT <seconds>                        # optional, defaults to 120
#   WORKING_DIRECTORY <dir>                  # optional, defaults to caller binary directory
#   ENVIRONMENT <VAR=value ...>)             # optional extra CTest environment
# cmake-format: on
# Add a private-framework unit-test executable and register it with CTest.
function(project_add_normal_unit_test)
  set(project_normal_unit_test_multi_value_args
      SOURCES
      LINK_LIBRARIES
      DEPENDENCIES
      INCLUDE_DIRECTORIES
      COMPILE_DEFINITIONS
      COMPILE_OPTIONS
      PCH_REUSE_FROM_TARGETS
      LABELS
      ENVIRONMENT)
  cmake_parse_arguments(PROJECT_NORMAL_UNIT_TEST "" "TARGET;COMPONENT;CATEGORY;TIMEOUT;WORKING_DIRECTORY"
                        "${project_normal_unit_test_multi_value_args}" ${ARGN})

  if(PROJECT_NORMAL_UNIT_TEST_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "project_add_normal_unit_test: unknown arguments: "
                        "${PROJECT_NORMAL_UNIT_TEST_UNPARSED_ARGUMENTS}")
  endif()
  if(PROJECT_NORMAL_UNIT_TEST_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "project_add_normal_unit_test: missing values for: "
                        "${PROJECT_NORMAL_UNIT_TEST_KEYWORDS_MISSING_VALUES}")
  endif()
  if(NOT PROJECT_NORMAL_UNIT_TEST_TARGET)
    message(FATAL_ERROR "project_add_normal_unit_test: TARGET is required")
  endif()
  if(NOT PROJECT_NORMAL_UNIT_TEST_COMPONENT)
    message(FATAL_ERROR "project_add_normal_unit_test: COMPONENT is required")
  endif()
  if(NOT PROJECT_NORMAL_UNIT_TEST_SOURCES)
    message(FATAL_ERROR "project_add_normal_unit_test: SOURCES is required")
  endif()
  if(TARGET "${PROJECT_NORMAL_UNIT_TEST_TARGET}")
    message(FATAL_ERROR "project_add_normal_unit_test: target ${PROJECT_NORMAL_UNIT_TEST_TARGET} already exists")
  endif()
  if(NOT COMMAND atframe_add_test_executable)
    message(FATAL_ERROR "project_add_normal_unit_test: atframe_add_test_executable is unavailable; enable the "
                        "atframe_utils tests before adding project unit tests")
  endif()

  set(PROJECT_NORMAL_UNIT_TEST_FRAME_DIR "${ATFRAMEWORK_ATFRAME_UTILS_REPO_DIR}/test")
  if(NOT IS_DIRECTORY "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}")
    message(FATAL_ERROR "project_add_normal_unit_test: private test framework not found: "
                        "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}")
  endif()

  # atframe_add_test_executable resolves these variables dynamically from its caller. Set them here instead of relying
  # on variables that are local to the atframe_utils/test directory.
  set(PROJECT_TEST_INC_DIR "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}")
  unset(PROJECT_TEST_DEFINITIONS)
  unset(PROJECT_TEST_LIB_LINK)
  atframe_add_test_executable(
    ${PROJECT_NORMAL_UNIT_TEST_TARGET} "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}/app/main.cpp"
    "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}/frame/test_case_base.cpp"
    "${PROJECT_NORMAL_UNIT_TEST_FRAME_DIR}/frame/test_manager.cpp" ${PROJECT_NORMAL_UNIT_TEST_SOURCES})

  # atframe_add_test_executable uses the plain target_link_libraries signature when GTest or Boost.Test is available.
  # Keep the same signature here so every supported dependency configuration can be generated by CMake.
  target_link_libraries(${PROJECT_NORMAL_UNIT_TEST_TARGET} ${ATFRAMEWORK_ATFRAME_UTILS_LINK_NAME}
                        ${PROJECT_NORMAL_UNIT_TEST_LINK_LIBRARIES})
  if(PROJECT_NORMAL_UNIT_TEST_DEPENDENCIES)
    add_dependencies(${PROJECT_NORMAL_UNIT_TEST_TARGET} ${PROJECT_NORMAL_UNIT_TEST_DEPENDENCIES})
  endif()
  if(PROJECT_NORMAL_UNIT_TEST_INCLUDE_DIRECTORIES)
    target_include_directories(${PROJECT_NORMAL_UNIT_TEST_TARGET}
                               PRIVATE ${PROJECT_NORMAL_UNIT_TEST_INCLUDE_DIRECTORIES})
  endif()
  if(PROJECT_COMMON_PRIVATE_INCLUDE_DIRECTORIES)
    target_include_directories(${PROJECT_NORMAL_UNIT_TEST_TARGET} PRIVATE ${PROJECT_COMMON_PRIVATE_INCLUDE_DIRECTORIES})
  endif()
  if(PROJECT_NORMAL_UNIT_TEST_COMPILE_DEFINITIONS)
    target_compile_definitions(${PROJECT_NORMAL_UNIT_TEST_TARGET}
                               PRIVATE ${PROJECT_NORMAL_UNIT_TEST_COMPILE_DEFINITIONS})
  endif()
  target_compile_options(${PROJECT_NORMAL_UNIT_TEST_TARGET} PRIVATE ${PROJECT_COMMON_PRIVATE_COMPILE_OPTIONS}
                                                                    ${PROJECT_NORMAL_UNIT_TEST_COMPILE_OPTIONS})
  if(PROJECT_COMMON_PRIVATE_LINK_OPTIONS)
    target_link_options(${PROJECT_NORMAL_UNIT_TEST_TARGET} PRIVATE ${PROJECT_COMMON_PRIVATE_LINK_OPTIONS})
  endif()

  project_tool_split_target_debug_sybmol(${PROJECT_NORMAL_UNIT_TEST_TARGET})
  project_tool_set_target_runtime_output_directory(
    "${PROJECT_TEST_RUNTIME_OUTPUT_DIRECTORY}" ${PROJECT_NORMAL_UNIT_TEST_TARGET} WITH_TARGET_RPATH WITH_ARCHIVE_RPATH)

  # Reuse the highest-weight PCH exported by linked libraries. Resolve aliases because the PCH helper requires real
  # target properties and cannot read them from an ALIAS target.
  set(PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATES
      ${ATFRAMEWORK_ATFRAME_UTILS_LINK_NAME} ${PROJECT_NORMAL_UNIT_TEST_LINK_LIBRARIES}
      ${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_FROM_TARGETS})
  set(PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_TARGETS)
  foreach(PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATE IN LISTS PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATES)
    if(NOT TARGET "${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATE}")
      continue()
    endif()
    get_target_property(PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_ALIAS "${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATE}"
                        ALIASED_TARGET)
    if(PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_ALIAS)
      list(APPEND PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_TARGETS "${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_ALIAS}")
    else()
      list(APPEND PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_TARGETS "${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_CANDIDATE}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_TARGETS)
  project_pch_tool_set_precompile_headers(${PROJECT_NORMAL_UNIT_TEST_TARGET} FOLDER "${PROJECT_NAME}/test"
                                          REUSE_FROM_TARGET ${PROJECT_NORMAL_UNIT_TEST_PCH_REUSE_TARGETS})

  set_target_properties(
    ${PROJECT_NORMAL_UNIT_TEST_TARGET}
    PROPERTIES INSTALL_RPATH_USE_LINK_PATH YES
               BUILD_WITH_INSTALL_RPATH NO
               BUILD_RPATH_USE_ORIGIN YES)
  set_property(TARGET ${PROJECT_NORMAL_UNIT_TEST_TARGET} PROPERTY FOLDER "${PROJECT_NAME}/test")

  project_setup_runtime_post_build_bash(${PROJECT_NORMAL_UNIT_TEST_TARGET}
                                        PROJECT_RUNTIME_POST_BUILD_EXECUTABLE_LIBRARY_BASH)
  project_setup_runtime_post_build_pwsh(${PROJECT_NORMAL_UNIT_TEST_TARGET}
                                        PROJECT_RUNTIME_POST_BUILD_EXECUTABLE_LIBRARY_PWSH)

  if(NOT PROJECT_NORMAL_UNIT_TEST_WORKING_DIRECTORY)
    set(PROJECT_NORMAL_UNIT_TEST_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  file(MAKE_DIRECTORY "${PROJECT_NORMAL_UNIT_TEST_WORKING_DIRECTORY}")

  add_test(NAME ${PROJECT_NORMAL_UNIT_TEST_TARGET}.unit COMMAND $<TARGET_FILE:${PROJECT_NORMAL_UNIT_TEST_TARGET}>)

  if(NOT PROJECT_NORMAL_UNIT_TEST_CATEGORY)
    set(PROJECT_NORMAL_UNIT_TEST_CATEGORY "component")
  endif()
  set(PROJECT_NORMAL_UNIT_TEST_ALL_LABELS ${PROJECT_NAME} unit normal-unit-test
                                          "${PROJECT_NORMAL_UNIT_TEST_CATEGORY}:${PROJECT_NORMAL_UNIT_TEST_COMPONENT}")
  list(APPEND PROJECT_NORMAL_UNIT_TEST_ALL_LABELS ${PROJECT_NORMAL_UNIT_TEST_LABELS})
  list(REMOVE_DUPLICATES PROJECT_NORMAL_UNIT_TEST_ALL_LABELS)

  if(NOT PROJECT_NORMAL_UNIT_TEST_TIMEOUT)
    set(PROJECT_NORMAL_UNIT_TEST_TIMEOUT 120)
  endif()
  set_tests_properties(
    ${PROJECT_NORMAL_UNIT_TEST_TARGET}.unit
    PROPERTIES LABELS "${PROJECT_NORMAL_UNIT_TEST_ALL_LABELS}" TIMEOUT "${PROJECT_NORMAL_UNIT_TEST_TIMEOUT}"
               WORKING_DIRECTORY "${PROJECT_NORMAL_UNIT_TEST_WORKING_DIRECTORY}")

  if(WIN32)
    set(PROJECT_NORMAL_UNIT_TEST_PATH_MODIFICATIONS "PATH=path_list_prepend:${PROJECT_TEST_RUNTIME_OUTPUT_DIRECTORY}")
    if(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
      list(APPEND PROJECT_NORMAL_UNIT_TEST_PATH_MODIFICATIONS
           "PATH=path_list_prepend:${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
      # Multi-config generators keep shared libraries in a per-config subdirectory; $<CONFIG> resolves to the
      # configuration CTest runs, so only that subdirectory joins PATH.
      if(CMAKE_CONFIGURATION_TYPES)
        list(APPEND PROJECT_NORMAL_UNIT_TEST_PATH_MODIFICATIONS
             "PATH=path_list_prepend:${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/$<CONFIG>")
      endif()
    endif()
    if(PROJECT_THIRD_PARTY_INSTALL_DIR)
      list(APPEND PROJECT_NORMAL_UNIT_TEST_PATH_MODIFICATIONS
           "PATH=path_list_prepend:${PROJECT_THIRD_PARTY_INSTALL_DIR}/bin")
    endif()
    set_property(
      TEST ${PROJECT_NORMAL_UNIT_TEST_TARGET}.unit
      APPEND
      PROPERTY ENVIRONMENT_MODIFICATION "${PROJECT_NORMAL_UNIT_TEST_PATH_MODIFICATIONS}")
  endif()

  if(PROJECT_NORMAL_UNIT_TEST_ENVIRONMENT)
    set_property(
      TEST ${PROJECT_NORMAL_UNIT_TEST_TARGET}.unit
      APPEND
      PROPERTY ENVIRONMENT "${PROJECT_NORMAL_UNIT_TEST_ENVIRONMENT}")
  endif()
endfunction()
