{{- template "libapp.configmap" (list . "dtmq-proxysvr.configmap") -}}
{{- define "dtmq-proxysvr.configmap" -}}
data:
  {{ include "dtmq-proxysvr.name" . }}.yaml: {{ tpl (.Files.Get "cfg/dtmq-proxysvr.yaml.tpl") . | quote }}
{{- end -}}
