<%!
    import common.project_utils as project
%>
; =========== DB ===========
[db]
cluster.host = ${project.get_global_option('db', 'cluster_default_host', '127.0.0.1:7001')}
raw.host = ${project.get_global_option('db', 'single_default_host', '127.0.0.1:6379')}

script.login = login.lua
script.user = user.lua

timer.retry = 100ms    ; retry wait time(microsecond)
timer.timeout = 75s    ; timeout(second)
timer.proc = 128ms     ; proc interval(milisecond)