# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: authsvrd

type_id: 11
type_name: "authsvr"

image:
  repository: harbor.atframe.work/atsf4g-co/authsvr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/authsvr/cfg
  logMountPath: /data/atframework/publish/authsvr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/authsvr/log
redis:
  enable: true

cs_session:
  enable: true

authsvr:
  version_conf: ../cfg/cfg_version.xml # version file
  strategy_conf: ../cfg/cfg_strategy.loginsvr.xml # strategy file
  # cdn_url:                                         # cdn url
  # debug_platform: 0                                # debug platform mode
  start_time: 0 # service start time
  end_time: 0 # service end time
  # white_openid_list:                               # white openid list, can ignore start time and end time
  backend:
    router:
      type_id: 12
      type_name: lobbysvr
      policy: hash # random/round_robin/hash
      # policy_selector:
      #   api_version: apps/v1
      #   kind: StatefulSet
      #   name: authsvr
      #   namespace_name: atframework.shared
      #   service_subset: ""
      #   labels:
      #     district: cn
    relogin_expire: 14400

enable_session_manager: true
