# Default values for ranksvr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: rank-board-svrd

# 服务唯一ID标识
type_id: 15
type_name: "rank-board-svr"

image:
  repository: harbor.m-oa.com:6023/project-x/rank-board-svr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/rank-board-svr/cfg
  logMountPath: /data/atframework/publish/rank-board-svr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/rank-board-svr/log

service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP

redis:
  enable: true

ranksvr_ranking:
  rank_slave_num: 1
  rank_dunmp_task_max_num: 20
  rank_refresh_limit_second_interval: 60s
  rank_max_batch_get_num: 20
  max_mirror_count: 10
  rank_history_version_max_count: 20
  rank_slice_max_count: 200
  rank_tree_degree: 20
  rank_save_interval: 600
  rank_btree_degree: 20
  publisher_configure:
    gc_expire_duration: 3600
    gc_log_size: 30
    max_log_size: 300
