include_guard(GLOBAL)

set(ATFRAMEWORK_EXPORT_PACKAGE_NAME "atframework")
set(ATFRAMEWORK_EXPORT_TARGET_NAME "${ATFRAMEWORK_EXPORT_PACKAGE_NAME}-target")

set(ATFRAMEWORK_SERVICE_COMPONENT_DIR "${CMAKE_CURRENT_LIST_DIR}/service/component")
set(ATFRAMEWORK_SERVICE_COMPONENT_LINK_NAME atservice_component)

set(ATFRAMEWORK_SERVICE_GATEWAY_PROTOCOL_DIR "${CMAKE_CURRENT_LIST_DIR}/service/atgateway/protocols")
set(ATFRAMEWORK_SERVICE_GATEWAY_VERSION "0.1.0")
set(ATFRAMEWORK_SERVICE_GATEWAY_SERVER_SDK "atgateway-server-api")
set(ATFRAMEWORK_SERVICE_GATEWAY_CLIENT_SDK "atgateway-protocol-api")
