set(ATFRAMEWORK_SERVICE_COMPONENT_DIR "${CMAKE_CURRENT_LIST_DIR}/service/component")
set(ATFRAMEWORK_SERVICE_COMPONENT_LINK_NAME atservice_component)

set(ATFRAMEWORK_SERVICE_GATEWAY_PROTOCOL_DIR "${CMAKE_CURRENT_LIST_DIR}/service/atgateway/protocols")
set(ATFRAMEWORK_SERVICE_GATEWAY_VERSION "0.1.0")
set(ATFRAMEWORK_SERVICE_GATEWAY_LINK_NAME "atgateway-protocol")

# export library
include("${CMAKE_CURRENT_LIST_DIR}/export/export.macro.cmake")
