include("${CMAKE_CURRENT_LIST_DIR}/atframework.internal-functions.cmake")
atframework_write_package_config("${ATFRAMEWORK_EXPORT_PACKAGE_NAME}")

# framework repository
if(NOT TARGET ${ATFRAMEWORK_ATFRAME_UTILS_LINK_NAME}
   AND ATFRAMEWORK_ATFRAME_UTILS_REPO_DIR
   AND EXISTS "${ATFRAMEWORK_ATFRAME_UTILS_REPO_DIR}/CMakeLists.txt")
  add_subdirectory("${ATFRAMEWORK_ATFRAME_UTILS_REPO_DIR}")
endif()

if(NOT TARGET ${ATFRAMEWORK_LIBATBUS_LINK_NAME}
   AND ATFRAMEWORK_LIBATBUS_REPO_DIR
   AND EXISTS "${ATFRAMEWORK_LIBATBUS_REPO_DIR}/CMakeLists.txt")
  add_subdirectory("${ATFRAMEWORK_LIBATBUS_REPO_DIR}")
endif()

if(NOT TARGET ${ATFRAMEWORK_LIBATAPP_LINK_NAME}
   AND ATFRAMEWORK_LIBATAPP_REPO_DIR
   AND EXISTS "${ATFRAMEWORK_LIBATAPP_REPO_DIR}/CMakeLists.txt")
  add_subdirectory("${ATFRAMEWORK_LIBATAPP_REPO_DIR}")
endif()

# Basic services
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/service")

# Export
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/export")
