# add tool to binding loginsvr rpcs
generate_for_pb_add_cs_service(
  "${PROJECT_NAMESPACE}.LoginsvrClientService"
  "${CMAKE_CURRENT_LIST_DIR}/service"
  RPC_IGNORE_EMPTY_REQUEST
  TASK_PATH_PREFIX
  "logic"
  HANDLE_PATH_PREFIX
  "app"
  PROJECT_NAMESPACE
  "${PROJECT_NAMESPACE}"
  SERVICE_DLLEXPORT_DECL
  LOGINCLIENT_SERVICE_API
  RPC_DLLEXPORT_DECL
  LOGINCLIENT_RPC_API)
