# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: echosvrd

type_id: 10
type_name: "echosvr"

image:
  repository: harbor.atframe.work/atsf4g-co/echosvr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/echosvr/cfg
  logMountPath: /data/atframework/publish/echosvr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/echosvr/log

redis:
  enable: true
