# Default values for ranksvr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: rank-settlement-svrd

type_id: 14
type_name: "rank-settlement-svr"

image:
  repository: harbor.atframe.work/atsf4g-co/rank-settlement-svr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/rank-settlement-svr/cfg
  logMountPath: /data/atframework/publish/rank-settlement-svr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/rank-settlement-svr/log

service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP

redis:
  enable: true

ranksvr_settlement:
  settle_interval: 60
  settle_loop_count: 100
  disable_rank_settlemnet_clear: false
