syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;

import "protocol/extension/atframework.proto";

package orbit;

enum EnOrbitErrorCode {
  EN_ORBIT_ERROR_CODE_SUCCESS = 0;
  EN_ORBIT_ERROR_CODE_PARAM_ERROR = -50000000;
  EN_ORBIT_ERROR_CODE_RPC_NAME_ERROR = -50000001;
  EN_ORBIT_ERROR_CODE_METHOD_NOT_FOUND = -50000002;
  EN_ORBIT_ERROR_CODE_TIMEOUT = -50000003;
  EN_ORBIT_ERROR_CODE_ALREADY_REGISTER_ACTION = -50000004;
  EN_ORBIT_ERROR_CODE_SERIALIZETOSTRING = -50000005;
  EN_ORBIT_ERROR_CODE_MALLOC = -50000006;
  EN_ORBIT_ERROR_CODE_RPC_NAME_NOTFOUND = -50000007;
  EN_ORBIT_ERROR_CODE_TASK_ACTION_EMPTY = -50000008;
  EN_ORBIT_ERROR_CODE_TASK_ACTION_NOTFOUND = -50000009;
  EN_ORBIT_ERROR_CODE_PARSE_MESSAGE_FAILED = -50000010;
  EN_ORBIT_ERROR_CODE_MESSAGE_HEAD_NOT_FOUND = -50000011;
  EN_ORBIT_ERROR_CODE_CALL_AFTER_INIT = -50000012;
}

enum EnClientState {
  EN_CLIENT_STATE_UNSPECIFIED = 0;
  EN_CLIENT_STATE_STARTING = 1;
  EN_CLIENT_STATE_RUNNING = 2;
  EN_CLIENT_STATE_EXITING = 3;
  EN_CLIENT_STATE_EXITED = 4;
}

enum EnClientExitReason {
  EN_CLIENT_EXIT_REASON_UNSPECIFIED = 0;
  EN_CLIENT_EXIT_REASON_NORMAL = 1;
  EN_CLIENT_EXIT_REASON_CRASH = 2;
  EN_CLIENT_EXIT_REASON_HEARTBEAT_TIMEOUT = 3;
  EN_CLIENT_EXIT_REASON_STARTUP_TIMEOUT = 4;
  EN_CLIENT_EXIT_STARTUP_FAILED = 5;
}

message DClientLoadSnapshot {
  // Client 的运行状态
  double cpu_used = 1;
  double memory_used_mb = 2;
}

message DAgentIdentity {
  uint64 agent_server_id = 1;
}

message DClientId {
  string client_id = 1;
}

message DClientIdentity {
  // 两个参数才能唯一确定一个Client
  DAgentIdentity agent_identity = 1;
  DClientId client_id = 2;
}

message DServerIdentity {
  uint64 unique_id = 1;
  uint64 server_node_id = 2;
}

message DClientMessage {
  DClientIdentity client_identity = 1;
  bytes payload = 2;
}

message DClientStartArgs {
  DClientId client_id = 1;
  repeated string custom_args = 2;
}

message DAgentClientStartArgsResource {
  double normal_cpu = 1;
  double normal_memory_mb = 2;
  double seed_cpu = 3;
  double seed_memory_mb = 4;
}

message DAgentClientStartArgs {
  DClientStartArgs client_start_args = 1;
  uint32 startup_timeout_sec = 2;
  uint32 heartbeat_timeout_sec = 3;
  DAgentClientStartArgsResource resource = 4;
  string match_tag = 5; // 数据截至到Controller后无用
}

message DAgentLoadSnapshot {
  double cpu_used = 1;
  double memory_used_mb = 2;
  uint32 running_client_count = 3;
  uint32 starting_client_count = 4;
}

message DAgentEtcdLoadRecord {
  uint64 server_id = 1;
  string region = 2;
  string tag = 3;
  double cpu_capacity = 4;
  double memory_capacity_mb = 5;
  int32 max_batch_startup_count = 6;
  bool seed_mode = 7;
  bool agent_online = 8;

  DAgentLoadSnapshot agent = 11;
}

message DOrbitGroupInfo {
  string region = 1;
  string tag = 2;
}

/////////////// RPC 接入层 ///////////////

message OrbitRpcMessageHead {
  // 通用数据
  sint32 error_code = 1;
  int64 timestamp = 2;
  uint64 sequence = 3;

  // Session和任务信息
  uint64 source_task_id = 11;
  uint64 destination_task_id = 12;

  oneof rpc_type {
    atframework.RpcRequestMeta rpc_request = 31;
    atframework.RpcResponseMeta rpc_response = 32;
    atframework.RpcStreamMeta rpc_stream = 33;
  }
  atframework.RpcTraceSpan rpc_trace = 34;  // 用于链路追踪
}

message OrbitRpcMessage {
  OrbitRpcMessageHead head = 1;
  bytes body_bin = 3;
}