{{- template "libapp.configmap" (list . "atgateway.configmap") -}}
{{- define "atgateway.configmap" -}}
data:
  {{ include "atgateway.name" . }}.yaml: {{ tpl (.Files.Get "cfg/atgateway.yaml.tpl") . | quote }}
{{- end -}}
