syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/timestamp.proto";

package atframework.dtmq;

message channel_subscriber {
  uint64 subscriber_server_id = 1;
  // Suggestion: type:...
  // - User: "U:{zone_id}:{user_id}"
  // - Team: "T:{team_id}"
  // - Guild: "G:{guild_id}"
  // - Role: "R:{zone_id}:{user_id}:{role_id}"
  string subscriber_key = 2;

  // 默认情况下，正常的订阅请求不会返回私有数据，而是仅通过pull获取。
  // 但是在主从同步和某些特殊场景下，订阅者需要实时同步私有数据，这时候可以通过这个标记来获取。
  bool with_private_data = 6;

  google.protobuf.Timestamp last_heartbeat_timepoint = 10;
  int64 last_heartbeat_sequence = 11;
  uint64 last_heartbeat_hash_code = 12;
}

message channel_page_info {
  // 页码
  int64 page_start_sequence = 1;
  // 每页数量
  int64 page_size = 2;
  // 是否有更多数据
  bool page_more = 3;
}
