syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

package atframework.orbit;

import "protocol/common/orbit.common.proto";

/////////////// Agent -> Client ///////////////
service AgentToClientService {
  rpc forward_to_client(ATDForwardToClientReq) returns (DTAForwardToClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "转发Server消息"
    };
  };
  rpc fork_seed_client(ATDForkSeedClientReq) returns (DTAForkSeedClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "Fork方式启动Client"
    };
  };
  rpc stop_client(stream ATDStopClientReq) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "停止Client"
    };
  };
}

message ATDForwardToClientReq {
  bytes payload = 1;
}
message DTAForwardToClientRsp {
  int32 error_code = 1;
}

message ATDForkSeedClientReq {
  uint64 app_id = 1;
  DClientStartArgs start_args = 2;
}
message DTAForkSeedClientRsp {
  int32 error_code = 1;
  int32 pid = 2;
}

message ATDStopClientReq {
  EnClientExitReason reason = 1;
}

/////////////// Client -> Agent ///////////////
service ClientToAgentService {
  // 上报 Client 心跳
  rpc client_heartbeat(stream DTAClientHeartbeatNotify) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "上报心跳"
    };
  };
  // 发送自定义消息
  rpc send_to_server(DTASendToServerReq) returns (ATDSendToServerRsp) {
    option (atframework.rpc_options) = {
      api_name: "发送至Server"
      allow_no_wait: true
    };
  };
  // 上报 Client 状态
  rpc client_start(DTAClientStartReq) returns (ATDClientStartRsp) {
    option (atframework.rpc_options) = {
      api_name: "Client启动成功"
    };
  };
  rpc client_exit(DTAClientExitReq) returns (ATDClientExitRsp) {
    option (atframework.rpc_options) = {
      api_name: "Client退出"
    };
  };
}

message DTAClientHeartbeatNotify {
  DClientId client_id = 1;
  DClientLoadSnapshot snapshot = 2;
}

message DTASendToServerReq {
  DClientId client_id = 1;
  bytes payload = 2;
}
message ATDSendToServerRsp {
  int32 error_code = 1;
}

message DTAClientStartReq {
  DClientId client_id = 1;
  string client_addr = 2;
  bytes custom_data = 3;
}
message ATDClientStartRsp {
  int32 error_code = 1;
}

message DTAClientExitReq {
  DClientId client_id = 1;

  EnClientExitReason exit_reason = 11;
  bytes custom_data = 12;
  int32 exit_code = 13;
}
message ATDClientExitRsp {
  int32 error_code = 1;
}