# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: atgatewayd

type_id: 2
type_name: "atgateway"

image:
  repository: harbor.m-oa.com:6023/project-x/atgateway
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/atgateway/cfg
  logMountPath: /data/atframework/publish/atgateway/log

vector:
  enabled: false
  log_path: /data/atframework/publish/atgateway/log


service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP