# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: dtcoordsvrd

type_id: 13
type_name: "dtcoordsvr"

image:
  repository: harbor.atframe.work/atsf4g-co/server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

volumeMounts:
  configMountPath: /data/atframework/publish/dtcoordsvr/cfg
  logMountPath: /data/atframework/publish/dtcoordsvr/log

vector:
  enabled: true
  log_path: /data/atframework/publish/dtcoordsvr/log

service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP

redis:
  enable: true

webserver:
  port: 7001

# websocket:
# websocket 路径片段 实际路径为 /<deployment_environment>/daily/ws/v1
# path: daily
