version: "3"

tasks:
  generate-protocol-pb:
    desc: "Generate Protocol pb"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - |
        mkdir -p "{{.OUTPUT_DIR}}"
        echo -e "\033[34;1m Generate pb protocol... \033[0m"
        if [ "{{OS}}" = "windows" ]; then
          "{{.PROTOC_EXEC_BIN}}" --proto_path=../../../server_frame/protocol/public --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' ../../../server_frame/protocol/public/protocol/common/*.proto ../../../server_frame/protocol/public/protocol/config/*.proto ../../../server_frame/protocol/public/protocol/extension/*.proto ../../../server_frame/protocol/public/protocol/pbdesc/*.proto '{{.XRES_PROTOCOL_PATH}}/core/protocol/extension/v3/*.proto' '{{.XRES_PROTOCOL_PATH}}/core/protocol/config/pb_header_v3.proto' '{{.XRES_PROTOCOL_PATH}}/code/protocol/extension/xrescode_extensions_v3.proto' -o "{{.OUTPUT_DIR}}/ALL.pb"
        else
          "{{.PROTOC_EXEC_BIN}}" --proto_path=../../../server_frame/protocol/public --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' ../../../server_frame/protocol/public/protocol/common/*.proto ../../../server_frame/protocol/public/protocol/config/*.proto ../../../server_frame/protocol/public/protocol/extension/*.proto ../../../server_frame/protocol/public/protocol/pbdesc/*.proto {{.XRES_PROTOCOL_PATH}}/core/protocol/extension/v3/*.proto '{{.XRES_PROTOCOL_PATH}}/core/protocol/config/pb_header_v3.proto' '{{.XRES_PROTOCOL_PATH}}/code/protocol/extension/xrescode_extensions_v3.proto' -o "{{.OUTPUT_DIR}}/ALL.pb"
        fi
        echo -e "\033[34;1m Generate pb protocol... done \033[0m"
    silent: true

  generate-protocol-code:
    desc: "Generate Protocol code"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - |
        echo -e "\033[34;1m Generate code protocol... \033[0m"
        "{{.PROTOC_EXEC_BIN}}" --go_out=./ --mutable_out=./ --go_opt=paths=source_relative --mutable_opt=paths=source_relative --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' --proto_path=../../../server_frame/protocol/public  ../../../server_frame/protocol/public/protocol/common/*.proto
        "{{.PROTOC_EXEC_BIN}}" --go_out=./ --mutable_out=./ --go_opt=paths=source_relative --mutable_opt=paths=source_relative --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' --proto_path=../../../server_frame/protocol/public ../../../server_frame/protocol/public/protocol/extension/*.proto
        "{{.PROTOC_EXEC_BIN}}" --go_out=./ --mutable_out=./ --go_opt=paths=source_relative --mutable_opt=paths=source_relative --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' --proto_path=../../../server_frame/protocol/public ../../../server_frame/protocol/public/protocol/config/*.proto
        "{{.PROTOC_EXEC_BIN}}" --go_out=./ --mutable_out=./ --go_opt=paths=source_relative --mutable_opt=paths=source_relative --proto_path='{{.XRES_PROTOCOL_PATH}}/core' --proto_path='{{.XRES_PROTOCOL_PATH}}/code' --proto_path=../../../server_frame/protocol/public ../../../server_frame/protocol/public/protocol/pbdesc/*.proto

        echo -e "\033[34;1m Generate code protocol... done \033[0m"
    silent: true