set(GENERATE_FOR_PB_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(GENERATE_FOR_PB_SERVER_PID_FILE "${CMAKE_BINARY_DIR}/generate-for-pb-run.server.pid")
set(GENERATE_FOR_PB_SERVER_PORT_FILE "${CMAKE_BINARY_DIR}/generate-for-pb-run.server.port")
set(GENERATE_FOR_PB_IPC_PY "${GENERATE_FOR_PB_SOURCE_DIR}/tools/generate-for-pb/generator_ipc.py")
set(GENERATE_FOR_PB_MAKO_PY "${GENERATE_FOR_PB_SOURCE_DIR}/tools/generate-for-pb/mako-generator.py")
set(GENERATE_FOR_PB_JINJA2_PY "${GENERATE_FOR_PB_SOURCE_DIR}/tools/generate-for-pb/jinja2-generator.py")
set(GENERATE_FOR_PB_WORK_DIR "${CMAKE_BINARY_DIR}")
set(GENERATE_FOR_PB_OUT_SH "${CMAKE_BINARY_DIR}/generate-for-pb-run.sh")
set(GENERATE_FOR_PB_OUT_PWSH "${CMAKE_BINARY_DIR}/generate-for-pb-run.ps1")
set(GENERATE_FOR_PB_PROTO_SH "${CMAKE_BINARY_DIR}/generate-for-pb-generate-pb.sh")
set(GENERATE_FOR_PB_PROTO_PWSH "${CMAKE_BINARY_DIR}/generate-for-pb-generate-pb.ps1")
set(GENERATE_FOR_PB_OUT_LOG "${CMAKE_BINARY_DIR}/generate-for-pb-run.log")
set(GENERATE_FOR_PB_TARGET "generate-for-pb")
unset(GENERATE_FOR_PB_PROTO_COMMAND)
file(WRITE "${GENERATE_FOR_PB_OUT_LOG}" "# generate-for-pb-run")
if(NOT PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR)
  set(PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR "${PROJECT_THIRD_PARTY_INSTALL_DIR}/.python_modules")
endif()
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.11.0")
  set(GENERATE_FOR_PB_PY_ENCODING ENCODING "UTF-8")
elseif(CMAKE_VERSION VERSION_GREATER_EQUAL "3.8.0")
  set(GENERATE_FOR_PB_PY_ENCODING ENCODING "UTF8")
else()
  unset(GENERATE_FOR_PB_PY_ENCODING)
endif()
# Python3_EXECUTABLE
if(NOT Python3_EXECUTABLE)
  find_package(Python3 COMPONENTS Interpreter)
  if(NOT Python_Interpreter_FOUND)
    message(FATAL_ERROR "python3/python is required.")
  endif()
endif()

set(GENERATE_FOR_PB_CLEANUP_SERVER_TARGET "generate-for-pb-cleanup-server")
set(GENERATE_FOR_PB_CLEANUP_SERVER_SCRIPT "${CMAKE_BINARY_DIR}/generate-for-pb-cleanup-server.cmake")

# Create a build-time target that shuts down any stale generate-for-pb server before generation runs. Every
# command/target that drives the mako/jinja2 template engine depends on this target, so the cleanup runs exactly once at
# the beginning of each build (not once per flow), and all generation work runs afterwards while sharing a single
# freshly started server.
function(generate_for_pb_setup_cleanup_server_target)
  if(TARGET ${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET})
    return()
  endif()

  set(_generate_for_pb_cleanup_encoding_arg "")
  list(LENGTH GENERATE_FOR_PB_PY_ENCODING _generate_for_pb_cleanup_encoding_len)
  if(_generate_for_pb_cleanup_encoding_len GREATER_EQUAL 2)
    list(GET GENERATE_FOR_PB_PY_ENCODING 1 _generate_for_pb_cleanup_encoding_value)
    set(_generate_for_pb_cleanup_encoding_arg "ENCODING \"${_generate_for_pb_cleanup_encoding_value}\"")
  endif()

  file(
    WRITE "${GENERATE_FOR_PB_CLEANUP_SERVER_SCRIPT}"
    "# Auto-generated by generate_for_pb_utility.cmake. Do not edit.
# Shutdown any stale generate-for-pb server so each build starts from a clean server.
execute_process(
  COMMAND
    \"${Python3_EXECUTABLE}\" \"${GENERATE_FOR_PB_MAKO_PY}\"
    \"--server-pid-file\" \"${GENERATE_FOR_PB_SERVER_PID_FILE}\"
    \"--server-port-file\" \"${GENERATE_FOR_PB_SERVER_PORT_FILE}\"
    \"--server-timeout\" \"1\" \"--no-server-auto-start\" \"--server-shutdown\" \"--add-package-prefix\"
    \"${PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR}\"
  RESULT_VARIABLE _generate_for_pb_shutdown_result
  WORKING_DIRECTORY \"${GENERATE_FOR_PB_WORK_DIR}\"
  OUTPUT_VARIABLE _generate_for_pb_shutdown_stdout
  ERROR_VARIABLE _generate_for_pb_shutdown_stderr ${_generate_for_pb_cleanup_encoding_arg})
if(NOT _generate_for_pb_shutdown_result EQUAL 0)
  message(
    FATAL_ERROR
      \"Cleanup old generate-for-pb server failed: \${_generate_for_pb_shutdown_stderr}\${_generate_for_pb_shutdown_stdout}\")
endif()

set(_generate_for_pb_shutdown_wait_count 0)
while(EXISTS \"${GENERATE_FOR_PB_SERVER_PID_FILE}\" AND _generate_for_pb_shutdown_wait_count LESS 5)
  math(EXPR _generate_for_pb_shutdown_wait_count \"\${_generate_for_pb_shutdown_wait_count} + 1\")
  execute_process(COMMAND \"${CMAKE_COMMAND}\" -E sleep 1)
endwhile()

if(EXISTS \"${GENERATE_FOR_PB_SERVER_PID_FILE}\")
  file(READ \"${GENERATE_FOR_PB_SERVER_PID_FILE}\" _generate_for_pb_shutdown_pid)
  string(STRIP \"\${_generate_for_pb_shutdown_pid}\" _generate_for_pb_shutdown_pid)
  message(
    FATAL_ERROR
      \"Old generate-for-pb server did not exit after shutdown request. pid file: ${GENERATE_FOR_PB_SERVER_PID_FILE}, pid: \${_generate_for_pb_shutdown_pid}\")
endif()
")

  add_custom_target(
    ${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET}
    COMMAND "${CMAKE_COMMAND}" -P "${GENERATE_FOR_PB_CLEANUP_SERVER_SCRIPT}"
    WORKING_DIRECTORY "${GENERATE_FOR_PB_WORK_DIR}"
    COMMENT "Cleanup old generate-for-pb server")
  set_property(TARGET ${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET} PROPERTY FOLDER "${PROJECT_NAME}/codegen")

  execute_process(COMMAND "${CMAKE_COMMAND}" -P "${GENERATE_FOR_PB_CLEANUP_SERVER_SCRIPT}"
                  WORKING_DIRECTORY "${GENERATE_FOR_PB_WORK_DIR}")
endfunction()

generate_for_pb_setup_cleanup_server_target()

set(GENERATE_FOR_PB_PROROC_BIN ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_PROTOBUF_BIN_PROTOC})
if(NOT GENERATE_FOR_PB_PROROC_BIN)
  message(FATAL_ERROR "Protobuf - protoc is required.")
endif()

set(GENERATE_FOR_PB_CONF_ROOT_DIR "${CMAKE_BINARY_DIR}/_generated/generate-for-pb")
set(GENERATE_FOR_PB_CONF_DIR "${GENERATE_FOR_PB_CONF_ROOT_DIR}/conf")
file(MAKE_DIRECTORY "${GENERATE_FOR_PB_CONF_DIR}")

function(generate_for_pb_build_conf_header OUTPUT_VAR)
  set(multiValueArgs PB_FILES)
  cmake_parse_arguments(GENERATE_FOR_PB_HEADER "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  # 处理输入 PB_FILES 第一个是input 后面都是 external
  unset(_generate_for_pb_input_pb_file)
  unset(_generate_for_pb_external_pb_files)

  if(NOT GENERATE_FOR_PB_HEADER_PB_FILES)
    message(FATAL_ERROR "No input PB file specified for generate_for_pb_build_conf_header")
  endif()

  list(LENGTH GENERATE_FOR_PB_HEADER_PB_FILES _list_len)
  list(GET GENERATE_FOR_PB_HEADER_PB_FILES 0 _generate_for_pb_input_pb_file)

  if(_list_len GREATER 1)
    list(SUBLIST GENERATE_FOR_PB_HEADER_PB_FILES 1 -1 _generate_for_pb_external_pb_files)
  endif()

  set(_generate_for_pb_header
      "configure:
  encoding: 'UTF-8'
  output_directory: 'output directory'
  overwrite: ${_generate_for_pb_configure_overwrite}
  paths:
    - \"${ATFRAMEWORK_CMAKE_TOOLSET_DIR}/modules\"")
  foreach(GENERATE_FOR_PB_ARGS_ADD_PATH GENERATE_FOR_PB_MODULE_PROTOBUF_PYTHON_PATH
                                        GENERATE_FOR_PB_MODULE_MAKO_PYTHON_PATH GENERATE_FOR_PB_MODULE_SIX_PYTHON_PATH)
    if(${GENERATE_FOR_PB_ARGS_ADD_PATH})
      string(APPEND _generate_for_pb_header "
    - \"${${GENERATE_FOR_PB_ARGS_ADD_PATH}}\"")
    endif()
  endforeach()

  string(
    APPEND
    _generate_for_pb_header
    "
  package_prefix:
    - \"${PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR}\"
  protocol_project_directory: '${PROJECT_SOURCE_DIR}'
  protocol_input_pb_file: '${_generate_for_pb_input_pb_file}'")

  if(_generate_for_pb_external_pb_files)
    string(APPEND _generate_for_pb_header "
  protocol_external_pb_files:")
    foreach(_generate_for_pb_external_pb_file IN LISTS _generate_for_pb_external_pb_files)
      string(APPEND _generate_for_pb_header "
    - '${_generate_for_pb_external_pb_file}'")
    endforeach()
  else()
    string(APPEND _generate_for_pb_header "
  protocol_external_pb_files: [ ]")
  endif()

  string(
    APPEND
    _generate_for_pb_header
    "

rules:
  # Rules to generate rpc codes
")
  set(${OUTPUT_VAR}
      "${_generate_for_pb_header}"
      PARENT_SCOPE)
endfunction()

function(generate_for_pb_parse_output_files PRINT_STDOUT OUTPUT_VAR)
  string(REGEX MATCHALL "[^\r\n]+" _generate_for_pb_print_lines "${PRINT_STDOUT}")

  set(_generate_for_pb_all_outputs)
  foreach(_generate_for_pb_print_line IN LISTS _generate_for_pb_print_lines)
    if(NOT _generate_for_pb_print_line)
      continue()
    endif()

    list(APPEND _generate_for_pb_all_outputs "${_generate_for_pb_print_line}")
  endforeach()

  if(_generate_for_pb_all_outputs)
    list(REMOVE_DUPLICATES _generate_for_pb_all_outputs)
  endif()

  set(${OUTPUT_VAR}
      "${_generate_for_pb_all_outputs}"
      PARENT_SCOPE)
endfunction()

function(generate_for_pb_print_output_files RULE_FILE OUTPUT_VAR)
  set(_generate_for_pb_run_print_output_files_options
      "${Python3_EXECUTABLE}"
      "${GENERATE_FOR_PB_MAKO_PY}"
      "--server-pid-file"
      "${GENERATE_FOR_PB_SERVER_PID_FILE}"
      "--server-port-file"
      "${GENERATE_FOR_PB_SERVER_PORT_FILE}"
      "--server-auto-start"
      "--client-mode"
      "--add-package-prefix"
      "${PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR}"
      "--print-output-files"
      "--quiet"
      "-c"
      "${RULE_FILE}")
  if(PROJECT_TOOL_CLANG_FORMAT)
    list(APPEND _generate_for_pb_run_print_output_files_options "--clang-format-path" "${PROJECT_TOOL_CLANG_FORMAT}")
  endif()
  execute_process(
    COMMAND ${_generate_for_pb_run_print_output_files_options}
    RESULT_VARIABLE _generate_for_pb_print_result
    WORKING_DIRECTORY "${GENERATE_FOR_PB_WORK_DIR}"
    OUTPUT_VARIABLE _generate_for_pb_print_stdout
    ERROR_VARIABLE _generate_for_pb_print_stderr ${GENERATE_FOR_PB_PY_ENCODING})
  if(NOT _generate_for_pb_print_result EQUAL 0)
    message(
      FATAL_ERROR
        "Print output files for ${FLOW_ID} failed: ${_generate_for_pb_print_stderr}${_generate_for_pb_print_stdout}")
  endif()
  generate_for_pb_parse_output_files("${_generate_for_pb_print_stdout}" _generate_for_pb_print_files)
  set(${OUTPUT_VAR}
      "${_generate_for_pb_print_files}"
      PARENT_SCOPE)
endfunction()

# 1. 处理需要传出的即将生成的文件列表
function(generate_for_pb_codegen_flow FLOW_NAME)
  # 2. 生成 Target 让最终代码生成转为依赖项 Target 为 FLOW_NAME
  set(options "")
  set(oneValueArgs RULE_BODY_HEAD OVERWRITE_RULE_BODY NON_OVERWRITE_RULE_BODY)
  set(multiValueArgs TEMPLATE_DEPENDS PROTOCOL_TARGET) # 依赖的Protocol 默认依赖
  cmake_parse_arguments(GENERATE_FOR_PB_CODEGEN_FLOW "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT GENERATE_FOR_PB_CODEGEN_FLOW_RULE_BODY_HEAD)
    message(FATAL_ERROR "Missing required argument RULE_BODY_HEAD for generate_for_pb_codegen_flow")
    return()
  endif()
  if(NOT GENERATE_FOR_PB_CODEGEN_FLOW_OVERWRITE_RULE_BODY AND NOT GENERATE_FOR_PB_CODEGEN_FLOW_NON_OVERWRITE_RULE_BODY)
    message(FATAL_ERROR "Missing required argument OVERWRITE_RULE_BODY or NON_OVERWRITE_RULE_BODY for generate_for_pb_codegen_flow")
  endif()

  set(_generate_for_pb_rule_file "${GENERATE_FOR_PB_CONF_DIR}/${FLOW_NAME}.rule.yaml") # 最终生成使用
  set(_generate_for_pb_overwrite_rule_file) # 打印使用
  set(_generate_for_pb_non_overwrite_rule_file) # 打印使用
  set(_generate_for_pb_target_name "${GENERATE_FOR_PB_TARGET}-${FLOW_NAME}")

  # 处理依赖的协议生成目标的PBFILE
  unset(__CONF_PB_FILES)
  foreach(PROTOCOL_TARGET IN LISTS GENERATE_FOR_PB_CODEGEN_FLOW_PROTOCOL_TARGET)
    if(NOT TARGET ${PROTOCOL_TARGET})
      message(FATAL_ERROR "Target ${PROTOCOL_TARGET} does not exist.")
    endif()
    get_target_property(PROTOCOL_TARGET_PB_FILES "${PROTOCOL_TARGET}" "PBFILE")
    if(PROTOCOL_TARGET_PB_FILES)
      list(APPEND __CONF_PB_FILES ${PROTOCOL_TARGET_PB_FILES})
    else()
      message(FATAL_ERROR "Target ${PROTOCOL_TARGET} does not have PBFILE property.")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES __CONF_PB_FILES)
  message(STATUS "generate_for_pb_codegen_flow: ${FLOW_NAME} with pb file: ${__CONF_PB_FILES}")

  # 生成配置头
  generate_for_pb_build_conf_header(_generate_for_pb_header PB_FILES "${__CONF_PB_FILES}")

  # 生成最终配置文件
  file(WRITE "${_generate_for_pb_rule_file}" "${_generate_for_pb_header}${GENERATE_FOR_PB_CODEGEN_FLOW_RULE_BODY_HEAD}${GENERATE_FOR_PB_CODEGEN_FLOW_OVERWRITE_RULE_BODY}${GENERATE_FOR_PB_CODEGEN_FLOW_NON_OVERWRITE_RULE_BODY}")

  unset(_generate_for_pb_output_files)
  if(DEFINED GENERATE_FOR_PB_CODEGEN_FLOW_OVERWRITE_RULE_BODY AND NOT "${GENERATE_FOR_PB_CODEGEN_FLOW_OVERWRITE_RULE_BODY}"
                                                                STREQUAL "")
    set(_generate_for_pb_overwrite_rule_file
        "${GENERATE_FOR_PB_CONF_DIR}/${FLOW_NAME}.overwrite.rule.yaml")
    file(WRITE "${_generate_for_pb_overwrite_rule_file}" "${_generate_for_pb_header}${GENERATE_FOR_PB_CODEGEN_FLOW_RULE_BODY_HEAD}${GENERATE_FOR_PB_CODEGEN_FLOW_OVERWRITE_RULE_BODY}")
    # 打印输出文件
    generate_for_pb_print_output_files("${_generate_for_pb_overwrite_rule_file}" _generate_for_pb_overwrite_outputs)
    # 设为 GENERATED
    foreach(_generate_for_pb_overwrite_output IN LISTS _generate_for_pb_overwrite_outputs)
      set_source_files_properties(${_generate_for_pb_overwrite_output} PROPERTIES GENERATED TRUE)
    endforeach()
    list(APPEND _generate_for_pb_output_files ${_generate_for_pb_overwrite_outputs})
  endif()

  if(DEFINED GENERATE_FOR_PB_CODEGEN_FLOW_NON_OVERWRITE_RULE_BODY
     AND NOT "${GENERATE_FOR_PB_CODEGEN_FLOW_NON_OVERWRITE_RULE_BODY}" STREQUAL "")
    set(_generate_for_pb_non_overwrite_rule_file
        "${GENERATE_FOR_PB_CONF_DIR}/${FLOW_NAME}.non-overwrite.rule.yaml")
    file(WRITE "${_generate_for_pb_non_overwrite_rule_file}"
         "${_generate_for_pb_header}${GENERATE_FOR_PB_CODEGEN_FLOW_RULE_BODY_HEAD}${GENERATE_FOR_PB_CODEGEN_FLOW_NON_OVERWRITE_RULE_BODY}")
    # 打印输出文件
    generate_for_pb_print_output_files("${_generate_for_pb_non_overwrite_rule_file}" _generate_for_pb_non_overwrite_outputs)
    list(APPEND _generate_for_pb_output_files ${_generate_for_pb_non_overwrite_outputs})
  endif()
  list(REMOVE_DUPLICATES _generate_for_pb_output_files)

  # Target 注册
  set(__generate_for_pb_command_options
      "${Python3_EXECUTABLE}" "${GENERATE_FOR_PB_MAKO_PY}" "--server-pid-file" "${GENERATE_FOR_PB_SERVER_PID_FILE}"
      "--server-port-file" "${GENERATE_FOR_PB_SERVER_PORT_FILE}" "--server-auto-start" "--client-mode"
      "--add-package-prefix" "${PROJECT_THIRD_PARTY_PYTHON_MODULE_DIR}" "-c" "${_generate_for_pb_rule_file}")
  if(PROJECT_TOOL_CLANG_FORMAT)
    list(APPEND __generate_for_pb_command_options "--clang-format-path" "${PROJECT_TOOL_CLANG_FORMAT}")
  endif()

  add_custom_command(
    OUTPUT ${_generate_for_pb_output_files}
    COMMAND ${__generate_for_pb_command_options}
    WORKING_DIRECTORY "${GENERATE_FOR_PB_WORK_DIR}"
    DEPENDS "${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET}"
            "${_generate_for_pb_rule_file}"
            "${GENERATE_FOR_PB_MAKO_PY}"
            "${GENERATE_FOR_PB_IPC_PY}"
            ${GENERATE_FOR_PB_CODEGEN_FLOW_TEMPLATE_DEPENDS}
            ${__CONF_PB_FILES}
    COMMENT "Generate [@${GENERATE_FOR_PB_WORK_DIR}] ${FLOW_NAME}")
  add_custom_target(
    ${_generate_for_pb_target_name}
    DEPENDS ${_generate_for_pb_output_files}
    SOURCES ${_generate_for_pb_outputs})
  if(TARGET ${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET})
    # 依赖清理
    add_dependencies(${_generate_for_pb_target_name} ${GENERATE_FOR_PB_CLEANUP_SERVER_TARGET})
  endif()
  foreach(PROTOCOL_TARGET IN LISTS GENERATE_FOR_PB_CODEGEN_FLOW_PROTOCOL_TARGET)
    if(TARGET ${PROTOCOL_TARGET})
      # 依赖协议生成
      add_dependencies(${_generate_for_pb_target_name} ${PROTOCOL_TARGET})
    endif()
  endforeach()
  set_property(TARGET ${_generate_for_pb_target_name} PROPERTY FOLDER "${PROJECT_NAME}/codegen")

  # 变量导出
  unset(_generate_for_pb_outputs)
  list(APPEND _generate_for_pb_outputs ${_generate_for_pb_overwrite_outputs} ${_generate_for_pb_non_overwrite_outputs})
  set_property(TARGET ${_generate_for_pb_target_name} PROPERTY OUTPUT_FILE "${_generate_for_pb_outputs}")
endfunction()

# 收集本目录下的文件
function(generate_for_pb_collect_filtered_output_files ROOT_DIR OUTPUT_FILES SOURCE_OUTPUT_VAR HEADER_OUTPUT_VAR)
  get_filename_component(_generate_for_pb_root_dir "${ROOT_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  set(_generate_for_pb_filtered_source_files)
  set(_generate_for_pb_filtered_header_files)

  foreach(_generate_for_pb_output_file IN LISTS OUTPUT_FILES)
    if(NOT _generate_for_pb_output_file)
      continue()
    endif()

    if(IS_ABSOLUTE "${_generate_for_pb_output_file}")
      set(_generate_for_pb_output_file_abs "${_generate_for_pb_output_file}")
    else()
      get_filename_component(_generate_for_pb_output_file_abs "${_generate_for_pb_output_file}" ABSOLUTE BASE_DIR "${_generate_for_pb_root_dir}")
    endif()

    file(RELATIVE_PATH _generate_for_pb_relative_path "${_generate_for_pb_root_dir}" "${_generate_for_pb_output_file_abs}")
    
    if(_generate_for_pb_relative_path MATCHES "^\\.\\.([/\\\\]|$)")
      continue()
    endif()

    if(_generate_for_pb_output_file_abs MATCHES "\\.(c|cc|cpp|cxx)$")
      list(APPEND _generate_for_pb_filtered_source_files "${_generate_for_pb_output_file_abs}")
    elseif(_generate_for_pb_output_file_abs MATCHES "\\.(h|hh|hpp|hxx)$")
      list(APPEND _generate_for_pb_filtered_header_files "${_generate_for_pb_output_file_abs}")
    endif()
  endforeach()

  if(_generate_for_pb_filtered_source_files)
    list(REMOVE_DUPLICATES _generate_for_pb_filtered_source_files)
  endif()
  if(_generate_for_pb_filtered_header_files)
    list(REMOVE_DUPLICATES _generate_for_pb_filtered_header_files)
  endif()

  set(${SOURCE_OUTPUT_VAR} "${_generate_for_pb_filtered_source_files}" PARENT_SCOPE)
  set(${HEADER_OUTPUT_VAR} "${_generate_for_pb_filtered_header_files}" PARENT_SCOPE)
endfunction()

function(generate_for_pb_collect_output_from_flows FLOW_NAMES OUTPUT_VAR)
  foreach(FLOW_NAME IN LISTS FLOW_NAMES)
    set(_generate_for_pb_flow_target_name "${GENERATE_FOR_PB_TARGET}-${FLOW_NAME}")
    if(NOT TARGET ${_generate_for_pb_flow_target_name})
      message(FATAL_ERROR "Target ${_generate_for_pb_flow_target_name} does not exist. Make sure to call generate_for_pb_codegen_flow first.")
    endif()
    get_target_property(_generate_for_pb_flow_outputs "${_generate_for_pb_flow_target_name}" "OUTPUT_FILE")
    list(APPEND _generate_for_pb_all_outputs ${_generate_for_pb_flow_outputs})
  endforeach()
  if(_generate_for_pb_all_outputs)
    list(REMOVE_DUPLICATES _generate_for_pb_all_outputs)
    set(${OUTPUT_VAR} "${_generate_for_pb_all_outputs}" PARENT_SCOPE)
  endif()
endfunction()

function(generate_for_pb_add_dependencies TARGET_NAME FLOW_NAMES)
  foreach(FLOW_NAME IN LISTS FLOW_NAMES)
    set(_generate_for_pb_flow_target_name "${GENERATE_FOR_PB_TARGET}-${FLOW_NAME}")
    if(NOT TARGET ${_generate_for_pb_flow_target_name})
      message(FATAL_ERROR "Target ${_generate_for_pb_flow_target_name} does not exist. Make sure to call generate_for_pb_codegen_flow first.")
    endif()
    add_dependencies(${TARGET_NAME} ${_generate_for_pb_flow_target_name})
  endforeach()
endfunction()

function(generate_for_pb_add_custom_configure FLOW_NAME)
  set(GENERATE_FOR_PB_ARGS_OPTIONS)
  set(GENERATE_FOR_PB_ARGS_ONE_VALUE
      RULE_BODY_HEAD
      OVERWRITE_RULE
      NON_OVERWRITE_RULE)
  set(GENERATE_FOR_PB_ARGS_MULTI_VALUE PROTOCOL_TARGET TEMPLATE_DEPENDS)
  cmake_parse_arguments(generate_for_pb_add_custom_configure "${GENERATE_FOR_PB_ARGS_OPTIONS}" "${GENERATE_FOR_PB_ARGS_ONE_VALUE}"
                          "${GENERATE_FOR_PB_ARGS_MULTI_VALUE}" ${ARGN})

  generate_for_pb_codegen_flow(
    "${FLOW_NAME}"
    RULE_BODY_HEAD
    "${generate_for_pb_add_custom_configure_RULE_BODY_HEAD}"
    OVERWRITE_RULE_BODY
    "${generate_for_pb_add_custom_configure_OVERWRITE_RULE}"
    NON_OVERWRITE_RULE_BODY
    "${generate_for_pb_add_custom_configure_NON_OVERWRITE_RULE}"
    TEMPLATE_DEPENDS
    "${generate_for_pb_add_custom_configure_TEMPLATE_DEPENDS}"
    PROTOCOL_TARGET
    "${generate_for_pb_add_custom_configure_PROTOCOL_TARGET}")
endfunction()

function(generate_for_pb_add_ss_service SERVICE_NAME SERVICE_ROOT_DIR)
  set(GENERATE_FOR_PB_ARGS_OPTIONS RPC_IGNORE_EMPTY_REQUEST NO_RPC NO_SERVICE_TASK)
  set(GENERATE_FOR_PB_ARGS_ONE_VALUE
      TASK_PATH_PREFIX
      HANDLE_PATH_PREFIX
      PROJECT_NAMESPACE
      RPC_ROOT_DIR
      SERVICE_DLLEXPORT_DECL
      RPC_DLLEXPORT_DECL
      GENERATED_FLOW_NAME)
  set(GENERATE_FOR_PB_ARGS_MULTI_VALUE INCLUDE_HEADERS EXTERNAL_COMPONENT_PROTOCOLS EXTERNAL_SERVICE_PROTOCOLS)

  cmake_parse_arguments(GENERATE_FOR_PB_ARGS "${GENERATE_FOR_PB_ARGS_OPTIONS}" "${GENERATE_FOR_PB_ARGS_ONE_VALUE}"
                        "${GENERATE_FOR_PB_ARGS_MULTI_VALUE}" ${ARGN})
  if(NOT GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX)
    set(GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX ".")
  endif()
  if(GENERATE_FOR_PB_ARGS_HANDLE_PATH_PREFIX)
    set(HANDLE_PATH_PREFIX "${GENERATE_FOR_PB_ARGS_HANDLE_PATH_PREFIX}/")
  else()
    set(HANDLE_PATH_PREFIX "")
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE)
    set(GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE "")
  endif()
  if(GENERATE_FOR_PB_ARGS_RPC_IGNORE_EMPTY_REQUEST)
    set(GENERATE_FOR_PB_RPC_IGNORE_EMPTY_REQUEST "rpc_exclude_request: [ 'google.protobuf.Empty' ]")
  else()
    set(GENERATE_FOR_PB_RPC_IGNORE_EMPTY_REQUEST "rpc_exclude_request: [ ]")
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_RPC_ROOT_DIR)
    set(GENERATE_FOR_PB_ARGS_RPC_ROOT_DIR "${PROJECT_SERVER_FRAME_BAS_DIR}")
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL)
    string(REGEX REPLACE "[-\\.]" "_" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL "${SERVICE_NAME}")
    string(REGEX REPLACE "[\\\$\\\\/]" "" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL
                         "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}")
    string(REPLACE "::" "_" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL
                   "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}_API")
    string(TOUPPER "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL)
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL)
    string(REGEX REPLACE "_API\\$" "" GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL
                         "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}")
    string(TOUPPER "${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}_RPC_API" GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL)
  endif()
  if(GENERATE_FOR_PB_ARGS_INCLUDE_HEADERS)
    set(CUSTOM_INCLUDE_HEADERS "include_headers:")
    foreach(INCLUDE_HEADERS ${GENERATE_FOR_PB_ARGS_INCLUDE_HEADERS})
      set(CUSTOM_INCLUDE_HEADERS "${CUSTOM_INCLUDE_HEADERS}
          - '${INCLUDE_HEADERS}'")
    endforeach()
  else()
    set(CUSTOM_INCLUDE_HEADERS "include_headers: [ ]")
  endif()

  set(GENERATE_FOR_PB_RULE_HEAD
  "  # ${SERVICE_NAME} - rpc
  ")
  set(GENERATE_FOR_PB_OVERWRITE_RULE_BODY)
  set(GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY)
  set(GENERATE_FOR_PB_TEMPLATE_DEPENDS)

  if(NOT GENERATE_FOR_PB_ARGS_NO_RPC)
    set(GENERATE_FOR_PB_OVERWRITE_RULE_BODY
        "${GENERATE_FOR_PB_OVERWRITE_RULE_BODY}
  - service:
      name: '${SERVICE_NAME}'
      overwrite: true
      output_directory: '${GENERATE_FOR_PB_ARGS_RPC_ROOT_DIR}'
      service_dllexport_decl: '${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}'
      rpc_dllexport_decl: '${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}'
      custom_variables:
        project_namespace: '${GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE}'
        rpc_include_prefix: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}'
        ${CUSTOM_INCLUDE_HEADERS}
      service_template:
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/rpc_call_api_for_ss.h.mako'
          output: 'rpc/\${service.get_extension_field(\"service_options\", lambda x: x.module_name, service.get_name_lower_rule())}/\${service.get_name_lower_rule()}.atfw.gen.h'
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/rpc_call_api_for_ss.cpp.mako'
          output: 'rpc/\${service.get_extension_field(\"service_options\", lambda x: x.module_name, service.get_name_lower_rule())}/\${service.get_name_lower_rule()}.atfw.gen.cpp'
    ")
    list(APPEND GENERATE_FOR_PB_TEMPLATE_DEPENDS "${GENERATE_FOR_PB_SOURCE_DIR}/templates/rpc_call_api_for_ss.h.mako"
         "${GENERATE_FOR_PB_SOURCE_DIR}/templates/rpc_call_api_for_ss.cpp.mako")
  endif()

  if(NOT GENERATE_FOR_PB_ARGS_NO_SERVICE_TASK)
    set(GENERATE_FOR_PB_OVERWRITE_RULE_BODY
        "${GENERATE_FOR_PB_OVERWRITE_RULE_BODY}
  - service:
      name: '${SERVICE_NAME}'
      overwrite: true
      output_directory: '${SERVICE_ROOT_DIR}'
      service_dllexport_decl: '${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}'
      rpc_dllexport_decl: '${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}'
      custom_variables:
        project_namespace: '${GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE}'
        rpc_include_prefix: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}'
        ${CUSTOM_INCLUDE_HEADERS}
      service_template:
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_ss_rpc.h.mako'
          output: '${HANDLE_PATH_PREFIX}handle_ss_rpc_\${service.get_name_lower_rule()}.atfw.gen.h'
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_ss_rpc.cpp.mako'
          output: '${HANDLE_PATH_PREFIX}handle_ss_rpc_\${service.get_name_lower_rule()}.atfw.gen.cpp'
")
    set(GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY
        "${GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY}
  - service:
      name: '${SERVICE_NAME}'
      overwrite: true
      output_directory: '${SERVICE_ROOT_DIR}'
      service_dllexport_decl: '${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}'
      rpc_dllexport_decl: '${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}'
      custom_variables:
        project_namespace: '${GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE}'
        rpc_include_prefix: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}'
        ${CUSTOM_INCLUDE_HEADERS}
      rpc_template:
        - overwrite: false
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_ss_rpc.h.mako'
          output: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}/\${rpc.get_extension_field(\"rpc_options\", lambda x: x.module_name, \"action\")}/task_action_\${rpc.get_name()}.h'
        - overwrite: false
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_ss_rpc.cpp.mako'
          output: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}/\${rpc.get_extension_field(\"rpc_options\", lambda x: x.module_name, \"action\")}/task_action_\${rpc.get_name()}.cpp'
")
    list(
      APPEND
      GENERATE_FOR_PB_TEMPLATE_DEPENDS
      "${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_ss_rpc.h.mako"
      "${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_ss_rpc.cpp.mako"
      "${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_ss_rpc.h.mako"
      "${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_ss_rpc.cpp.mako")
  endif()

  # 处理PROTOCOLS TARGET 名字
  unset(__EXTERNAL_COMPONENT_PROTOCOLS)
  unset(__EXTERNAL_SERVICE_PROTOCOLS)
  foreach(GENERATE_FOR_PB_ARGS_EXTERNAL_COMPONENT_PROTOCOL IN LISTS GENERATE_FOR_PB_ARGS_EXTERNAL_COMPONENT_PROTOCOLS)
    if(NOT GENERATE_FOR_PB_ARGS_EXTERNAL_COMPONENT_PROTOCOL)
      continue()
    endif()
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
      list(APPEND __EXTERNAL_COMPONENT_PROTOCOLS "pc-${GENERATE_FOR_PB_ARGS_EXTERNAL_COMPONENT_PROTOCOL}")
    else()
      list(APPEND __EXTERNAL_COMPONENT_PROTOCOLS "${PROJECT_NAME}-component-${GENERATE_FOR_PB_ARGS_EXTERNAL_COMPONENT_PROTOCOL}")
    endif()
  endforeach()
  foreach(GENERATE_FOR_PB_ARGS_EXTERNAL_SERVICE_PROTOCOL IN LISTS GENERATE_FOR_PB_ARGS_EXTERNAL_SERVICE_PROTOCOLS)
    if(NOT GENERATE_FOR_PB_ARGS_EXTERNAL_SERVICE_PROTOCOL)
      continue()
    endif()
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
      list(APPEND __EXTERNAL_SERVICE_PROTOCOLS "pp-${GENERATE_FOR_PB_ARGS_EXTERNAL_SERVICE_PROTOCOL}")
    else()
      list(APPEND __EXTERNAL_SERVICE_PROTOCOLS "${PROJECT_NAME}-protocol-${GENERATE_FOR_PB_ARGS_EXTERNAL_SERVICE_PROTOCOL}")
    endif()
  endforeach()

  if (NOT GENERATE_FOR_PB_ARGS_GENERATED_FLOW_NAME)
    set(GENERATE_FOR_PB_ARGS_GENERATED_FLOW_NAME "${SERVICE_NAME}")
  endif()
  generate_for_pb_codegen_flow(
    "${GENERATE_FOR_PB_ARGS_GENERATED_FLOW_NAME}"
    RULE_BODY_HEAD
    "${GENERATE_FOR_PB_RULE_HEAD}"
    OVERWRITE_RULE_BODY
    "${GENERATE_FOR_PB_OVERWRITE_RULE_BODY}"
    NON_OVERWRITE_RULE_BODY
    "${GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY}"
    TEMPLATE_DEPENDS
    "${GENERATE_FOR_PB_TEMPLATE_DEPENDS}"
    PROTOCOL_TARGET
    "${SERVER_FRAME_BASE_PROTOCOLS}"
    "${__EXTERNAL_COMPONENT_PROTOCOLS}"
    "${__EXTERNAL_SERVICE_PROTOCOLS}")
endfunction(generate_for_pb_add_ss_service)

function(generate_for_pb_add_cs_service SERVICE_NAME SERVICE_ROOT_DIR)
  set(GENERATE_FOR_PB_ARGS_OPTIONS RPC_IGNORE_EMPTY_REQUEST)
  set(GENERATE_FOR_PB_ARGS_ONE_VALUE TASK_PATH_PREFIX HANDLE_PATH_PREFIX PROJECT_NAMESPACE SERVICE_DLLEXPORT_DECL
                                     RPC_DLLEXPORT_DECL)
  set(GENERATE_FOR_PB_ARGS_MULTI_VALUE INCLUDE_HEADERS)
  cmake_parse_arguments(GENERATE_FOR_PB_ARGS "${GENERATE_FOR_PB_ARGS_OPTIONS}" "${GENERATE_FOR_PB_ARGS_ONE_VALUE}"
                        "${GENERATE_FOR_PB_ARGS_MULTI_VALUE}" ${ARGN})
  if(NOT GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX)
    set(GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX ".")
  endif()
  if(GENERATE_FOR_PB_ARGS_HANDLE_PATH_PREFIX)
    set(HANDLE_PATH_PREFIX "${GENERATE_FOR_PB_ARGS_HANDLE_PATH_PREFIX}/")
  else()
    set(HANDLE_PATH_PREFIX "")
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE)
    set(GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE "")
  endif()
  if(GENERATE_FOR_PB_ARGS_RPC_IGNORE_EMPTY_REQUEST)
    set(GENERATE_FOR_PB_RPC_IGNORE_EMPTY_REQUEST "rpc_exclude_request: [ 'google.protobuf.Empty' ]")
  else()
    set(GENERATE_FOR_PB_RPC_IGNORE_EMPTY_REQUEST "rpc_exclude_request: [ ]")
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL)
    string(REGEX REPLACE "[-\\.]" "_" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL "${SERVICE_NAME}")
    string(REGEX REPLACE "[\\\$\\\\/]" "" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL
                         "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}")
    string(REPLACE "::" "_" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL
                   "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}_API")
    string(TOUPPER "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}" GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL)
  endif()
  if(NOT GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL)
    string(REGEX REPLACE "_API\\$" "" GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL
                         "${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}")
    string(TOUPPER "${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}_RPC_API" GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL)
  endif()
  if(GENERATE_FOR_PB_ARGS_INCLUDE_HEADERS)
    set(CUSTOM_INCLUDE_HEADERS "include_headers:")
    foreach(INCLUDE_HEADERS ${GENERATE_FOR_PB_ARGS_INCLUDE_HEADERS})
      set(CUSTOM_INCLUDE_HEADERS "${CUSTOM_INCLUDE_HEADERS}
          - '${INCLUDE_HEADERS}'")
    endforeach()
  else()
    set(CUSTOM_INCLUDE_HEADERS "include_headers: [ ]")
  endif()

  set(GENERATE_FOR_PB_RULE_HEAD
  "  # ${SERVICE_NAME}
  ")
  set(GENERATE_FOR_PB_OVERWRITE_RULE_BODY
        "
  - service:
      name: '${SERVICE_NAME}'
      overwrite: true
      output_directory: '${SERVICE_ROOT_DIR}'
      service_dllexport_decl: '${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}'
      rpc_dllexport_decl: '${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}'
      custom_variables:
        project_namespace: '${GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE}'
        rpc_include_prefix: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}'
        ${CUSTOM_INCLUDE_HEADERS}
      service_template:
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/session_downstream_api_for_cs.h.mako'
          output: 'rpc/\${service.get_extension_field(\"service_options\", lambda x: x.module_name, service.get_name_lower_rule())}/\${service.get_name_lower_rule()}.atfw.gen.h'
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/session_downstream_api_for_cs.cpp.mako'
          output: 'rpc/\${service.get_extension_field(\"service_options\", lambda x: x.module_name, service.get_name_lower_rule())}/\${service.get_name_lower_rule()}.atfw.gen.cpp'
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_cs_rpc.h.mako'
          output: '${HANDLE_PATH_PREFIX}handle_cs_rpc_\${service.get_name_lower_rule()}.atfw.gen.h'
        - overwrite: true
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_cs_rpc.cpp.mako'
          output: '${HANDLE_PATH_PREFIX}handle_cs_rpc_\${service.get_name_lower_rule()}.atfw.gen.cpp'
")
  set(GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY
        "
  - service:
      name: '${SERVICE_NAME}'
      overwrite: true
      output_directory: '${SERVICE_ROOT_DIR}'
      service_dllexport_decl: '${GENERATE_FOR_PB_ARGS_SERVICE_DLLEXPORT_DECL}'
      rpc_dllexport_decl: '${GENERATE_FOR_PB_ARGS_RPC_DLLEXPORT_DECL}'
      custom_variables:
        project_namespace: '${GENERATE_FOR_PB_ARGS_PROJECT_NAMESPACE}'
        rpc_include_prefix: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}'
        ${CUSTOM_INCLUDE_HEADERS}
      ${GENERATE_FOR_PB_RPC_IGNORE_EMPTY_REQUEST}
      rpc_template:
        - overwrite: false
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_cs_rpc.h.mako'
          output: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}/\${rpc.get_extension_field(\"rpc_options\", lambda x: x.module_name, \"action\")}/task_action_\${rpc.get_name()}.h'
        - overwrite: false
          input: '${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_cs_rpc.cpp.mako'
          output: '${GENERATE_FOR_PB_ARGS_TASK_PATH_PREFIX}/\${rpc.get_extension_field(\"rpc_options\", lambda x: x.module_name, \"action\")}/task_action_\${rpc.get_name()}.cpp'
")

  generate_for_pb_codegen_flow(
    "${SERVICE_NAME}"
    RULE_BODY_HEAD
    "${GENERATE_FOR_PB_RULE_HEAD}"
    OVERWRITE_RULE_BODY
    "${GENERATE_FOR_PB_OVERWRITE_RULE_BODY}"
    NON_OVERWRITE_RULE_BODY
    "${GENERATE_FOR_PB_NON_OVERWRITE_RULE_BODY}"
    TEMPLATE_DEPENDS
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/session_downstream_api_for_cs.h.mako"
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/session_downstream_api_for_cs.cpp.mako"
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_cs_rpc.h.mako"
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/handle_cs_rpc.cpp.mako"
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_cs_rpc.h.mako"
    "${GENERATE_FOR_PB_SOURCE_DIR}/templates/task_action_cs_rpc.cpp.mako"
    PROTOCOL_TARGET
    "${SERVER_FRAME_BASE_PROTOCOLS}")
endfunction(generate_for_pb_add_cs_service)

function(generate_for_pb_initialize_sh SCRIPT_PATH)
  set(optionArgs COMMAND_ECHO STOP_ON_ERROR)
  set(oneValueArgs SET_LOCATION)
  set(multiValueArgs "")
  cmake_parse_arguments(generate_for_pb_initialize_sh "${optionArgs}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  file(WRITE "${SCRIPT_PATH}" "#!/bin/bash${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")

  if(generate_for_pb_initialize_sh_STOP_ON_ERROR)
    file(APPEND "${SCRIPT_PATH}" "set -e ${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()
  if(generate_for_pb_initialize_sh_COMMAND_ECHO)
    file(APPEND "${SCRIPT_PATH}" "set -x ${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()
  if(generate_for_pb_initialize_sh_SET_LOCATION)
    file(APPEND "${SCRIPT_PATH}"
         "cd \"${generate_for_pb_initialize_sh_SET_LOCATION}\"${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()

  project_make_executable("${SCRIPT_PATH}")
endfunction()

function(generate_for_pb_initialize_pwsh SCRIPT_PATH)
  set(optionArgs COMMAND_ECHO STOP_ON_ERROR)
  set(oneValueArgs SET_LOCATION)
  set(multiValueArgs "")
  cmake_parse_arguments(generate_for_pb_initialize_pwsh "${optionArgs}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  file(WRITE "${SCRIPT_PATH}" "#!/usr/bin/env pwsh${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  file(APPEND "${SCRIPT_PATH}"
       "$PSDefaultParameterValues['*:Encoding'] = 'UTF-8'${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  file(APPEND "${SCRIPT_PATH}"
       "$OutputEncoding = [System.Text.UTF8Encoding]::new()${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")

  if(generate_for_pb_initialize_pwsh_STOP_ON_ERROR)
    file(APPEND "${SCRIPT_PATH}" "$ErrorActionPreference = \"Stop\"${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()
  if(generate_for_pb_initialize_pwsh_COMMAND_ECHO)
    file(APPEND "${SCRIPT_PATH}" "Set-PSDebug -Trace 1 ${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()

  if(generate_for_pb_initialize_pwsh_SET_LOCATION)
    file(APPEND "${SCRIPT_PATH}"
         "Set-Location \"${generate_for_pb_initialize_pwsh_SET_LOCATION}\"${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
  endif()

  project_make_executable("${SCRIPT_PATH}")
endfunction()