# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: lobbysvrd

type_id: 12
type_name: "lobbysvr"

image:
  repository: harbor.m-oa.com:6023/project-x/lobbysvr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/lobbysvr/cfg
  logMountPath: /data/atframework/publish/lobbysvr/log

# vector:
#   enabled: true
#   log_path: /data/atframework/publish/lobbysvr/log


vector:
  enabled: false
  log_path: /data/atframework/publish/lobbysvr/log

redis:
  enable: true

cachesvr_shared:
  enable: true

cs_session:
  enable: true

httproute:
  port: 7001
  parentRefsName: project-x-tls-gateway

lobbysvr:
  rank_auto_update_interval: 3600s