# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: lobbysvrd

type_id: 12
type_name: "lobbysvr"

image:
  repository: harbor.atframe.work/atsf4g-co/lobbysvr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  secrets: harbor-regcred

volumeMounts:
  configMountPath: /etc/atframework/publish/lobbysvr/cfg
  logMountPath: /data/atframework/publish/lobbysvr/log

# vector:
#   enabled: true
#   log_path: /data/atframework/publish/lobbysvr/log

vector:
  enabled: false
  log_path: /data/atframework/publish/lobbysvr/log

redis:
  enable: true

cachesvr_shared:
  enable: true

cs_session:
  enable: true

httproute:
  port: 7001
  parentRefsName: project-x-tls-gateway

lobbysvr:
  rank_auto_update_interval: 3600s
  chat:
    push_message_per_second: 3000
    push_message_buffer_max_count: 200000

enable_excel_config: true
enable_session_manager: true
