syntax = "proto3";

option optimize_for = SPEED;
// option optimize_for = LITE_RUNTIME;
// option optimize_for = CODE_SIZE;
// --cpp_out=lite:,--cpp_out=
option cc_enable_arenas = true;
option cc_generic_services = true;

import "google/protobuf/empty.proto";
import "protocol/extension/atframework.proto";

package orbit;

import "protocol/common/orbit.common.proto";

/////////////// Controller -> Agent ///////////////
service ControllerToAgentService {
  rpc start_client(CTAStartClientReq) returns (ATCStartClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "拉起Client 返回不等于可用"
    };
  };
  rpc forward_to_client(CTAForwardToClientReq) returns (ATCForwardToClientRsp) {
    option (atframework.rpc_options) = {
      api_name: "转发Client消息"
    };
  };
  rpc server_heartbeat(stream CTAServerHeartbeatReq) returns (google.protobuf.Empty) {
    option (atframework.rpc_options) = {
      api_name: "Server心跳"
    };
  };
}

message CTAStartClientReq {
  DServerIdentity server_identity = 1;

  DAgentClientStartArgs args = 2;
}
message ATCStartClientRsp {
  DAgentEtcdLoadRecord load_record = 1;
}

message CTAForwardToClientReq {
  DServerIdentity server_identity = 1;

  DClientId client_id = 2;
  bytes payload = 3;
}
message ATCForwardToClientRsp {}

message CTAServerHeartbeatReq {
  DServerIdentity server_identity = 1;
}